import {db} from '@qubere/db';
import type {SetupSummary} from '@qubere/entry-proof';
export async function loadClientSetup(accountId:string,clientId:string):Promise<SetupSummary|null> {
 const c=await db.client.findFirst({where:{id:clientId,accountId},include:{account:{select:{name:true}},onboardingCases:{orderBy:{createdAt:'desc'},take:1,include:{entities:{include:{poa:true,bond:true,importerOfRecord:true}}}},importersOfRecord:{orderBy:{createdAt:'asc'},include:{bond:true,powersOfAttorney:{orderBy:{createdAt:'desc'},take:1}}},clientDocuments:{where:{portalVisible:true,status:'ACTIVE'},select:{id:true,kind:true,title:true,expirationDate:true,sourceId:true}},clientStakeholders:{orderBy:{name:'asc'},select:{name:true,role:true,title:true,isSigner:true,loginStatus:true}}}});if(!c)return null;
 const onboarding=c.onboardingCases[0],entity=onboarding?.entities[0],importer=entity?.importerOfRecord??c.importersOfRecord[0],bond=entity?.bond??c.importersOfRecord[0]?.bond,poa=entity?.poa??c.importersOfRecord[0]?.powersOfAttorney[0];
 const stepStatus=(onboarding?.stepStatus??{}) as Record<string,unknown>;
 const labels=['Company details','Importer registration','Power of attorney','Customs bond','Screening','Activation'];
 const active=!!onboarding?.activatedAt||['active','activated'].includes(onboarding?.status??'');
 const team=onboarding?.assignedUserId?await db.accountMembership.findFirst({where:{accountId,userId:onboarding.assignedUserId,status:'ACTIVE',deletedAt:null,user:{deletedAt:null}},select:{user:{select:{firstName:true,lastName:true,email:true}}}}):null;
 const blockers=Array.isArray(onboarding?.blockers)?onboarding.blockers:[];
 // Only known blocker codes are copied. Internal screening notes never become customer text.
 const safeBlockers:Record<string,string>={POA_NOT_EXECUTED:'POA awaiting signature',BOND_NOT_VERIFIED:'Bond verification pending',SCREENING_INCOMPLETE:'Screening review pending',IMPORTER_NOT_REGISTERED:'Importer registration pending'};
 return {clientId:c.id,clientName:c.name,brokerName:c.account.name,onboarding:{status:onboarding?.status??'not_started',path:onboarding?.path??null,activatedAt:onboarding?.activatedAt?.toISOString()??null,steps:labels.map((label,i)=>({key:String(i+1),label,state:active?'done':stepStatus[String(i+1)]==='done'?'done':(onboarding?.currentStep??1)>i+1?'done':'pending'})),blockers:active?[]:[...new Set(blockers.map(b=>{const code=typeof b==='string'?b:b&&typeof b==='object'&&!Array.isArray(b)?String(b.code??''):'';return safeBlockers[code]??'Your broker is reviewing a setup requirement.'})),...(poa?.status!=='executed'?['POA awaiting signature']:[])]},importer:importer?{legalName:importer.name,ein:importer.irsEin?`••-•••${importer.irsEin.replace(/\D/g,'').slice(-4)}`:'Not on file',cbpImporterNumber:importer.cbpImporterNumber,registrationStatus:importer.registrationStatus}:null,bond:bond?{type:bond.bondType,surety:bond.suretyName,number:bond.bondNumber,amountUsd:Number(bond.bondAmount),activityCode:bond.activityCode,expirationDate:bond.expirationDate?.toISOString()??null,status:bond.status}:null,poa:poa?{status:poa.status,executionMethod:poa.executionMethod,signerName:poa.signerName,signedDate:poa.status==='executed'?poa.signedDate.toISOString():null,expirationDate:poa.expirationDate?.toISOString()??null,documentId:c.clientDocuments.find(d=>d.kind==='EXECUTED_POA'&&d.sourceId===poa.id)?.id??null}:null,screening:{status:entity?.screeningStatus??'pending',lastRunAt:entity?.updatedAt.toISOString()??null},documents:c.clientDocuments.map(d=>({id:d.id,kind:d.kind,title:d.title,expirationDate:d.expirationDate?.toISOString()??null})),stakeholders:c.clientStakeholders,brokerTeam:team?[{name:[team.user.firstName,team.user.lastName].filter(Boolean).join(' ')||'Your broker',role:'Assigned broker',email:team.user.email}]:[]};
}
