export enum AuditAction {
  // Document Operations
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_CLASSIFIED = "DOCUMENT_CLASSIFIED",
  DOCUMENT_REPROCESSED = "DOCUMENT_REPROCESSED",
  DOCUMENT_DELETED = "DOCUMENT_DELETED",
  DOCUMENT_STORED = "DOCUMENT_STORED",
  DOCUMENT_QUEUED = "DOCUMENT_QUEUED",
  FIELD_CORRECTED = "FIELD_CORRECTED",
  CLASSIFICATION_CHANGED = "CLASSIFICATION_CHANGED",

  // Decision & Exception Operations
  DECISION_APPROVED = "DECISION_APPROVED",
  DECISION_REJECTED = "DECISION_REJECTED",
  DECISION_AUTO_APPROVED = "DECISION_AUTO_APPROVED",
  DECISION_OVERRIDDEN = "DECISION_OVERRIDDEN",
  EXCEPTION_CREATED = "EXCEPTION_CREATED",
  EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED",
  EXCEPTION_WAIVED = "EXCEPTION_WAIVED",
  EXCEPTION_ASSIGNED = "EXCEPTION_ASSIGNED",

  // Filing Operations
  FILING_CREATED = "FILING_CREATED",
  FILING_SUBMITTED = "FILING_SUBMITTED",
  FILING_APPROVED = "FILING_APPROVED",
  FILING_TRANSMITTED = "FILING_TRANSMITTED",
  FILING_CANCELLED = "FILING_CANCELLED",
  FILING_RESUBMITTED = "FILING_RESUBMITTED",
  FILING_UPDATED = "FILING_UPDATED",
  FILING_VALIDATED = "FILING_VALIDATED",
  FILING_SEGREGATION_VIOLATION = "FILING_SEGREGATION_VIOLATION",

  // Product Master Operations
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED",
  PRODUCT_IMPORTED = "PRODUCT_IMPORTED",
  PRODUCT_CLASSIFIED = "PRODUCT_CLASSIFIED",
  PRODUCT_LINE_ATTACHED = "PRODUCT_LINE_ATTACHED",

  // Party Master Operations
  PARTY_CREATED = "PARTY_CREATED",
  PARTY_UPDATED = "PARTY_UPDATED",
  PARTY_ARCHIVED = "PARTY_ARCHIVED",
  PARTY_IMPORTED = "PARTY_IMPORTED",
  PARTY_SCREENED = "PARTY_SCREENED",
  PARTY_CONTACT_ADDED = "PARTY_CONTACT_ADDED",
  PARTY_CONTACT_REMOVED = "PARTY_CONTACT_REMOVED",
  PARTY_SITE_ADDED = "PARTY_SITE_ADDED",
  PARTY_SITE_REMOVED = "PARTY_SITE_REMOVED",

  // Advisory, Audit & Compliance
  ORIGIN_DETERMINED = "ORIGIN_DETERMINED",
  COMPLIANCE_AUDIT_RUN = "COMPLIANCE_AUDIT_RUN",
  REASONABLE_CARE_GENERATED = "REASONABLE_CARE_GENERATED",
  FOCUSED_ASSESSMENT_GENERATED = "FOCUSED_ASSESSMENT_GENERATED",
  ADVISORY_QUERIED = "ADVISORY_QUERIED",

  // Refunds & PSC
  REFUND_PSC_CREATED = "REFUND_PSC_CREATED",
  REFUND_PSC_UPDATED = "REFUND_PSC_UPDATED",
  PSC_READY_FOR_REVIEW = "PSC_READY_FOR_REVIEW",
  PSC_SUBMITTED = "PSC_SUBMITTED",
  PSC_WITHDRAWN = "PSC_WITHDRAWN",
  PSC_ACE_ACCEPTED = "PSC_ACE_ACCEPTED",
  PSC_ACE_REJECTED = "PSC_ACE_REJECTED",
  DRAWBACK_CLAIM_CREATED = "DRAWBACK_CLAIM_CREATED",
  DRAWBACK_CLAIM_SUBMITTED = "DRAWBACK_CLAIM_SUBMITTED",

  // Document Matching
  AUTO_ATTACH_DOCUMENT = "AUTO_ATTACH_DOCUMENT",

  // Reconciliation Operations
  RECONCILIATION_RUN = "RECONCILIATION_RUN",
  RECONCILIATION_ISSUE_RESOLVED = "RECONCILIATION_ISSUE_RESOLVED",
  RECONCILIATION_ISSUE_IGNORED = "RECONCILIATION_ISSUE_IGNORED",

  // Intake & System Operations
  INTAKE_SHIPMENT_CREATED = "INTAKE_SHIPMENT_CREATED",
  EMBARGO_SCREENING_QUERIED = "EMBARGO_SCREENING_QUERIED",
  EMBARGO_SCREENING_RESCREENED = "EMBARGO_SCREENING_RESCREENED",
  RESTRICTED_PARTY_SCREENING_QUERIED = "RESTRICTED_PARTY_SCREENING_QUERIED",
  RESTRICTED_PARTY_SCREENING_RESCREENED = "RESTRICTED_PARTY_SCREENING_RESCREENED",
  RESTRICTED_PARTY_DISPOSITION_UPDATED = "RESTRICTED_PARTY_DISPOSITION_UPDATED",
  PARTY_SCREENING_PRE_APPROVAL_CREATED = "PARTY_SCREENING_PRE_APPROVAL_CREATED",
  PARTY_SCREENING_PRE_APPROVAL_REVOKED = "PARTY_SCREENING_PRE_APPROVAL_REVOKED",
  PARTY_SCREENING_PRE_APPROVAL_REUSED = "PARTY_SCREENING_PRE_APPROVAL_REUSED",
  PARTY_SCREENING_PRE_APPROVAL_CHECK_INVALID = "PARTY_SCREENING_PRE_APPROVAL_CHECK_INVALID",
  PARTY_SCREENING_PRE_APPROVAL_BYPASSED_FORCE_RESCREEN = "PARTY_SCREENING_PRE_APPROVAL_BYPASSED_FORCE_RESCREEN",
  RPS_NOTIFICATION_QUEUED = "RPS_NOTIFICATION_QUEUED",
  RPS_NOTIFICATION_SENT = "RPS_NOTIFICATION_SENT",
  RPS_NOTIFICATION_RETRY = "RPS_NOTIFICATION_RETRY",
  RPS_NOTIFICATION_FAILED = "RPS_NOTIFICATION_FAILED",
  RPS_NOTIFICATION_SUPPRESSED = "RPS_NOTIFICATION_SUPPRESSED",
  RPS_NOTIFICATION_SETTINGS_UPDATED = "RPS_NOTIFICATION_SETTINGS_UPDATED",
  REGULATORY_RULING_INGESTED = "REGULATORY_RULING_INGESTED",
  AGENT_EXECUTION_COMPLETED = "AGENT_EXECUTION_COMPLETED",
  CLASSIFICATION_CASE_CREATED = "CLASSIFICATION_CASE_CREATED",
  CLASSIFICATION_CASE_DECIDED = "CLASSIFICATION_CASE_DECIDED",

  // Trade Data Governance (platform-admin rate review queue)
  TRADE_RATE_APPROVED = "TRADE_RATE_APPROVED",
  TRADE_RATE_REJECTED = "TRADE_RATE_REJECTED",

  // Compliance Keyword Rule Governance (platform-admin keyword-rule review queue)
  COMPLIANCE_KEYWORD_RULE_PUBLISHED = "COMPLIANCE_KEYWORD_RULE_PUBLISHED",
  COMPLIANCE_KEYWORD_RULE_REJECTED = "COMPLIANCE_KEYWORD_RULE_REJECTED",

  // Protests
  PROTEST_CREATED = "PROTEST_CREATED",
  PROTEST_READY_FOR_FILING = "PROTEST_READY_FOR_FILING",
  PROTEST_FILED = "PROTEST_FILED",
  PROTEST_WITHDRAWN = "PROTEST_WITHDRAWN",
  PROTEST_FRP_REQUESTED = "PROTEST_FRP_REQUESTED",
  PROTEST_STATUS_CHANGED = "PROTEST_STATUS_CHANGED",
  PROTEST_NOTE_ADDED = "PROTEST_NOTE_ADDED",

  // Community Screening
  COMMUNITY_SCREENING_RUN_CREATED = "COMMUNITY_SCREENING_RUN_CREATED",
  COMMUNITY_SCREENING_QUERIED = "COMMUNITY_SCREENING_QUERIED",
  COMMUNITY_SCREENING_RESCREENED = "COMMUNITY_SCREENING_RESCREENED",
  COMMUNITY_SCREENING_EXPORTED = "COMMUNITY_SCREENING_EXPORTED",

  // Bulk Compliance Screening
  COMPLIANCE_BATCH_CREATED = "COMPLIANCE_BATCH_CREATED",
  COMPLIANCE_BATCH_DOWNLOADED = "COMPLIANCE_BATCH_DOWNLOADED",
  COMPLIANCE_BATCH_CANCELLED = "COMPLIANCE_BATCH_CANCELLED",
  COMPLIANCE_BATCH_RETRIED = "COMPLIANCE_BATCH_RETRIED",
  COMPLIANCE_BATCH_RESCREENED = "COMPLIANCE_BATCH_RESCREENED",
  COMPLIANCE_BATCH_EXPIRED = "COMPLIANCE_BATCH_EXPIRED",

  // Continuous Party Monitoring (Reverse Denied-Party Screening / RDPS)
  RDPS_RUN_STARTED = "RDPS_RUN_STARTED",
  RDPS_RUN_COMPLETED = "RDPS_RUN_COMPLETED",
  RDPS_RUN_FAILED = "RDPS_RUN_FAILED",
  RDPS_WORSENING_DETECTED = "RDPS_WORSENING_DETECTED",
  RDPS_RECALL_VALIDATION_PASSED = "RDPS_RECALL_VALIDATION_PASSED",
  RDPS_RECALL_VALIDATION_FAILED = "RDPS_RECALL_VALIDATION_FAILED",
  RDPS_MANUAL_SCAN_TRIGGERED = "RDPS_MANUAL_SCAN_TRIGGERED",
  RDPS_RUN_EXPORTED = "RDPS_RUN_EXPORTED",
  RDPS_ALERT_DISPOSITIONED = "RDPS_ALERT_DISPOSITIONED",
  RDPS_REPORTS_EXPORTED = "RDPS_REPORTS_EXPORTED",
}

