vi.mock('@/modules/inbound/inboundNotifications', () => ({ summarizeInboundReceipt: vi.fn() }));
import { beforeEach, describe, expect, it, vi } from 'vitest';
const { db, attach } = vi.hoisted(() => ({ db: { $transaction: vi.fn(), $queryRaw: vi.fn(), inboundDocumentReview: { findFirst: vi.fn(), update: vi.fn() }, shipmentDocument: { findFirst: vi.fn(), update: vi.fn() }, shipment: { findFirst: vi.fn() }, client: { findFirst: vi.fn() }, inboundEmail: { update: vi.fn() }, documentShipmentCandidate: { deleteMany: vi.fn() }, auditLog: { create: vi.fn() } }, attach: vi.fn() }));
vi.mock('@/lib/db', () => ({ db }));
vi.mock('@/modules/inbound/inboundDocumentRouting', () => ({ attachInboundDocument: attach }));
vi.mock('@/modules/documents/processing/classificationExtraction', () => ({ runDocumentExtraction: vi.fn() }));
import { decideInboundReview } from '@/modules/inbound/inboundReviewService';
const row = { id: 'review', accountId: 'a', clientId: 'target', inboundEmailId: 'email', shipmentDocumentId: 'doc', status: 'OPEN', reason: 'NO_MATCH', shipmentDocument: { id: 'doc', clientId: 'target', shipmentId: null } };
beforeEach(() => { vi.resetAllMocks(); db.$transaction.mockImplementation(fn => fn(db)); db.inboundDocumentReview.findFirst.mockResolvedValue(row); db.shipmentDocument.findFirst.mockResolvedValue(row.shipmentDocument); db.shipment.findFirst.mockResolvedValue({ id: 'shipment' }); db.inboundDocumentReview.update.mockImplementation(({ data }) => ({ ...row, ...data })); });
describe('broker email decisions', () => {
  it('rejects a foreign review without touching its document', async () => { db.inboundDocumentReview.findFirst.mockResolvedValue(null); await expect(decideInboundReview('other', 'review', 'u', { action: 'discard' })).rejects.toThrow('REVIEW_NOT_FOUND'); expect(db.shipmentDocument.update).not.toHaveBeenCalled(); });
  it('requires the chosen shipment to belong to the current client and account', async () => { db.shipment.findFirst.mockResolvedValue(null); await expect(decideInboundReview('a', 'review', 'u', { action: 'resolve', shipmentId: 'foreign' })).rejects.toThrow('SHIPMENT_CLIENT_MISMATCH'); expect(db.shipmentDocument.update).not.toHaveBeenCalled(); });
  it('records a manual attachment, actor, and audit before refreshing proof', async () => { await decideInboundReview('a', 'review', 'broker', { action: 'resolve', shipmentId: 'shipment' }); expect(db.inboundDocumentReview.update).toHaveBeenCalledWith({ where: { id: 'review' }, data: expect.objectContaining({ status: 'RESOLVED', resolvedByUserId: 'broker', resolvedShipmentId: 'shipment' }) }); expect(attach).toHaveBeenCalledWith('a', 'doc', 'shipment', 'broker'); expect(db.auditLog.create).toHaveBeenCalled(); });
  it('does not reopen or discard a completed review', async () => { db.inboundDocumentReview.findFirst.mockResolvedValue({ ...row, status: 'RESOLVED' }); await expect(decideInboundReview('a', 'review', 'u', { action: 'discard' })).rejects.toThrow('REVIEW_ALREADY_DECIDED'); });
  it('discards an unattached file without deleting audit history', async () => { await decideInboundReview('a', 'review', 'u', { action: 'discard' }); expect(db.shipmentDocument.update).toHaveBeenCalledWith({ where: { id: 'doc' }, data: { status: 'DISCARDED', portalVisibility: 'INTERNAL' } }); expect(attach).not.toHaveBeenCalled(); });
  it('approves only this held email, never a permanent sender allowlist', async () => { db.inboundDocumentReview.findFirst.mockResolvedValue({ ...row, shipmentDocument: null, shipmentDocumentId: null, reason: 'UNKNOWN_SENDER' }); await decideInboundReview('a', 'review', 'u', { action: 'approve' }); expect(db.inboundEmail.update).toHaveBeenCalledWith({ where: { id: 'email' }, data: expect.objectContaining({ routingStatus: 'RECEIVED', senderApprovedAt: expect.any(Date) }) }); });
});
