import { beforeEach, describe, expect, it, vi } from 'vitest';
import { db } from '@/lib/db';
import { queuePortalUpdate, renderPortalEmail } from '@/lib/portal/portalNotifications';
let queued: any;
const recipient = { id: 'stakeholder1', email: 'customer@example.com', userId: 'u1', notifyPrefs: {} as Record<string, boolean> };
const mock = (model: string, method: string, fn: (...args: any[]) => any) => vi.spyOn((db as any)[model], method).mockImplementation(fn as any);
beforeEach(() => { vi.restoreAllMocks(); queued = null; recipient.notifyPrefs = {}; mock('clientStakeholder', 'findMany', async () => [recipient]); mock('accountMembership', 'findFirst', async () => ({ id: 'm1' })); mock('userClientAssignment', 'findUnique', async () => ({ id: 'a1' })); mock('complianceNotification', 'upsert', async ({ create }: any) => queued ?? (queued = { id: 'q1', ...create })); mock('complianceNotification', 'findUniqueOrThrow', async () => queued); mock('complianceNotification', 'update', async ({ data }: any) => Object.assign(queued, data)); mock('notification', 'create', async () => ({ id: 'n1' })); vi.spyOn(db, '$queryRaw').mockResolvedValue([]); vi.spyOn(db, '$transaction').mockImplementation((async (fn: (tx: any) => any) => fn(db)) as any); });
describe('Portal event outbox', () => {
    it('queues email and bell only once across retries', async () => { await queuePortalUpdate('account', 'target', 'ENTRY_PROOF_PUBLISHED', 'p1', '/entries/f1'); await queuePortalUpdate('account', 'target', 'ENTRY_PROOF_PUBLISHED', 'p1', '/entries/f1'); expect(db.notification.create).toHaveBeenCalledTimes(1); expect(queued.portalEventKey).toBe('account:target:ENTRY_PROOF_PUBLISHED:p1:stakeholder1'); expect(queued.recipients).toEqual(['customer@example.com']); expect(queued.deliveryStatus).toBe('PENDING'); });
    it('honors event preferences before queueing', async () => { recipient.notifyPrefs.ENTRY_PROOF_PUBLISHED = false; await queuePortalUpdate('account', 'target', 'ENTRY_PROOF_PUBLISHED', 'p1', '/entries/f1'); expect(db.complianceNotification.upsert).not.toHaveBeenCalled(); });
    it('honors independent email and portal preferences', async () => { recipient.notifyPrefs = { email: false, portal: false }; await queuePortalUpdate('account', 'target', 'ENTRY_PROOF_PUBLISHED', 'p1', '/entries/f1'); expect(queued).toMatchObject({ deliveryStatus: 'SUPPRESSED', recipients: [] }); expect(db.notification.create).not.toHaveBeenCalled(); });
    it('does not queue when the client assignment has been removed', async () => { vi.mocked(db.userClientAssignment.findUnique).mockResolvedValue(null); await queuePortalUpdate('account', 'target', 'ENTRY_PROOF_PUBLISHED', 'p1', '/entries/f1'); expect(db.complianceNotification.upsert).not.toHaveBeenCalled(); });
    it('renders only known event copy and a safe relative portal link', () => { expect(renderPortalEmail({ type: 'ENTRY_PROOF_PUBLISHED', href: '/entries/f1', recommendation: 'PRIVATE' }).text).not.toContain('PRIVATE'); expect(() => renderPortalEmail({ type: 'ENTRY_PROOF_PUBLISHED', href: '//evil.example' })).toThrow(); });
});
