export enum OpportunityType {
  CLASSIFICATION_REVIEW = "CLASSIFICATION_REVIEW",
  SECTION_301_EXCLUSION = "SECTION_301_EXCLUSION",
  TRADE_AGREEMENT = "TRADE_AGREEMENT",
  FIRST_SALE = "FIRST_SALE",
  DUTY_DRAWBACK = "DUTY_DRAWBACK",
  AD_CVD_SCOPE_EXCLUSION = "AD_CVD_SCOPE_EXCLUSION",
}
