import { generateSimplePdfBuffer } from "@/lib/pdf/pdfGenerator";
import type { ReportColumnDef } from "../catalog";

/** Rows beyond this are omitted from the PDF (the generator renders a single fixed-height page); CSV/XLSX remain the source of truth for full data. */
const PDF_MAX_ROWS = 120;

export interface PdfCriterion {
  label: string;
  value: string;
}

export function generateReportPdf(params: {
  reportName: string;
  columns: ReportColumnDef[];
  rows: Record<string, unknown>[];
  totalCount: number;
  criteria: PdfCriterion[];
  generatedBy: string;
  generatedAt: Date;
}): Buffer {
  const { reportName, columns, rows, totalCount, criteria, generatedBy, generatedAt } = params;
  const truncated = totalCount > PDF_MAX_ROWS;

  return generateSimplePdfBuffer({
    title: reportName,
    subtitle: "Compliance Report",
    metadata: {
      "Generated By": generatedBy,
      "Generated At": generatedAt.toISOString(),
      "Row Count": String(totalCount),
      ...(truncated ? { Note: `Showing first ${PDF_MAX_ROWS} of ${totalCount} rows -- export CSV/XLSX for the full dataset.` } : {}),
    },
    sections: [
      {
        heading: "Filter Criteria",
        items: criteria.length ? criteria.map((c) => ({ label: c.label, value: c.value })) : [{ label: "Filters", value: "None" }],
      },
    ],
    tables: [
      {
        heading: reportName,
        columns: columns.map((c) => ({ key: c.key, label: c.label })),
        rows: rows.slice(0, PDF_MAX_ROWS),
      },
    ],
  });
}
