import ExcelJS from "exceljs";
import type { ReportColumnDef } from "../catalog";

const FORMULA_PREFIXES = ["=", "+", "-", "@"];

function sanitizeCellValue(value: unknown): string | number | boolean | Date {
  if (value instanceof Date) return value;
  if (typeof value === "number" || typeof value === "boolean") return value;
  if (value === null || value === undefined) return "";
  const str = String(value);
  return FORMULA_PREFIXES.some((p) => str.startsWith(p)) ? `'${str}` : str;
}

export interface XlsxCriterion {
  label: string;
  value: string;
}

/** Generates an XLSX workbook with Summary, Details, and Criteria sheets. */
export async function generateXlsx(params: {
  reportName: string;
  columns: ReportColumnDef[];
  rows: Record<string, unknown>[];
  summary?: Record<string, number | string>;
  criteria: XlsxCriterion[];
  generatedBy: string;
  generatedAt: Date;
}): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Qubere Compliance Reports";
  workbook.created = params.generatedAt;

  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.addRow([params.reportName]).font = { bold: true, size: 14 };
  summarySheet.addRow([`Generated By: ${params.generatedBy}`]);
  summarySheet.addRow([`Generated At: ${params.generatedAt.toISOString()}`]);
  summarySheet.addRow([`Row Count: ${params.rows.length}`]);
  if (params.summary) {
    summarySheet.addRow([]);
    summarySheet.addRow(["Metric", "Value"]).font = { bold: true };
    for (const [key, value] of Object.entries(params.summary)) {
      summarySheet.addRow([key, value]);
    }
  }
  summarySheet.columns.forEach((col) => (col.width = 30));

  const detailsSheet = workbook.addWorksheet("Details");
  detailsSheet.columns = params.columns.map((c) => ({ header: c.label, key: c.key, width: 22 }));
  detailsSheet.getRow(1).font = { bold: true };
  detailsSheet.views = [{ state: "frozen", ySplit: 1 }];
  detailsSheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: params.columns.length },
  };
  for (const row of params.rows) {
    const values: Record<string, string | number | boolean | Date> = {};
    for (const col of params.columns) {
      values[col.key] = sanitizeCellValue(row[col.key]);
    }
    detailsSheet.addRow(values);
  }

  const criteriaSheet = workbook.addWorksheet("Criteria");
  criteriaSheet.addRow(["Filter", "Value"]).font = { bold: true };
  for (const c of params.criteria) {
    criteriaSheet.addRow([c.label, c.value]);
  }
  criteriaSheet.columns.forEach((col) => (col.width = 30));

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
