import { describe, it, expect, vi, beforeEach } from 'vitest';
const mocks = vi.hoisted(() => ({ ctx: { accountId: 'a1', userId: 'u1', roleNames: ['CUSTOMER_USER'], permissions: ['portal.entries.read', 'portal.entries.comment', 'portal.setup.read'], dataMode: 'DEMO' }, scope: { isAllClients: false, authorizedClientIds: ['target'], teamIds: [] }, filing: { id: 'f1', accountId: 'a1', shipmentId: 's1', customerVisibleAt: new Date(), shipment: { clientId: 'target', importerName: 'Target' } }, proof: { id: 'p1', accountId: 'a1', clientId: 'target', filingId: 'f1', shipmentId: 's1', version: 2, payload: { schemaVersion: 1, lines: [{ lineNumber: 1 }] } }, db: { customsFiling: { findUnique: vi.fn() }, entryProof: { findFirst: vi.fn() }, customerRequest: { create: vi.fn() }, entryProofEvent: { create: vi.fn() }, client: { findFirst: vi.fn() }, $transaction: vi.fn() } }));
vi.mock('../../../packages/auth/src/auth', () => ({ getAccountContext: vi.fn(async () => mocks.ctx) }));
vi.mock('../../../packages/auth/src/scope-engine', () => ({ getEffectiveUserScope: vi.fn(async () => mocks.scope) }));
vi.mock('@qubere/auth', async () => { const real = await import('../../../packages/auth/src/portal-auth'); return { ...real, getAccountContext: async () => mocks.ctx, getEffectiveUserScope: async () => mocks.scope }; });
vi.mock('@qubere/db', () => ({ db: mocks.db, withAccountIdContext: (_account: unknown, fn: () => unknown) => fn(), withDataModeContext: (_mode: unknown, fn: () => unknown) => fn(), isDataMode: () => true }));
const proofRoute = await import('../src/app/api/entries/[id]/proof/route');
const commentRoute = await import('../src/app/api/entries/[id]/proof/comments/route');
const params = { params: Promise.resolve({ id: 'f1' }) };
beforeEach(() => { vi.clearAllMocks(); mocks.ctx.roleNames = ['CUSTOMER_USER']; mocks.ctx.permissions = ['portal.entries.read', 'portal.entries.comment', 'portal.setup.read']; mocks.filing.accountId = 'a1'; mocks.filing.shipment.clientId = 'target'; mocks.filing.customerVisibleAt = new Date(); mocks.scope.authorizedClientIds = ['target']; mocks.db.customsFiling.findUnique.mockResolvedValue(mocks.filing); mocks.db.entryProof.findFirst.mockResolvedValue(mocks.proof); mocks.db.customerRequest.create.mockResolvedValue({ id: 'request1' }); mocks.db.$transaction.mockImplementation(async (fn: (tx: unknown) => unknown) => fn(mocks.db)); });
describe('Entry Proof HTTP handlers with actual portal authorization', () => {
    it('serves only the published payload with no-store', async () => { const r = await proofRoute.GET(new Request('http://portal/api/entries/f1/proof'), params); expect(r.status).toBe(200); expect(await r.json()).toEqual(mocks.proof.payload); expect(r.headers.get('Cache-Control')).toBe('no-store'); expect(mocks.db.entryProof.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ accountId: 'a1', status: 'PUBLISHED' }) })); });
    it('returns 404 before reading proof for another workspace', async () => { mocks.filing.accountId = 'amazon'; const r = await proofRoute.GET(new Request('http://portal/api/entries/f1/proof'), params); expect(r.status).toBe(404); expect(mocks.db.entryProof.findFirst).not.toHaveBeenCalled(); });
    it('does not reveal unpublished entry proof', async () => { mocks.filing.customerVisibleAt = null as any; expect((await proofRoute.GET(new Request('http://portal/api/entries/f1/proof'), params)).status).toBe(404); expect(mocks.db.entryProof.findFirst).not.toHaveBeenCalled(); });
    it('creates a question and event tied to the published version in one transaction', async () => { const r = await commentRoute.POST(new Request('http://portal/api/entries/f1/proof/comments', { method: 'POST', body: JSON.stringify({ lineNumber: 1, body: 'Why this HTS?' }) }), params); expect(r.status).toBe(201); expect(mocks.db.$transaction).toHaveBeenCalledTimes(1); expect(mocks.db.customerRequest.create).toHaveBeenCalledWith({ data: expect.objectContaining({ clientId: 'target', filingId: 'f1', type: 'QUESTION', metadata: { entryProofId: 'p1', entryProofVersion: 2, entryProofLineNumber: 1 }, messages: { create: expect.objectContaining({ authorType: 'CUSTOMER', body: 'Why this HTS?' }) } }) }); expect(mocks.db.entryProofEvent.create).toHaveBeenCalled(); });
    it('rejects a nonexistent line without writing', async () => { const r = await commentRoute.POST(new Request('http://portal/comments', { method: 'POST', body: JSON.stringify({ lineNumber: 99, body: 'Question' }) }), params); expect(r.status).toBe(400); expect(mocks.db.customerRequest.create).not.toHaveBeenCalled(); });
    it('enforces read-only role on question handler', async () => { mocks.ctx.permissions = ['portal.entries.read']; mocks.ctx.roleNames = ['CUSTOMER_VIEWER']; const r = await commentRoute.POST(new Request('http://portal/comments', { method: 'POST', body: JSON.stringify({ body: 'Question' }) }), params); expect(r.status).toBe(404); expect(mocks.db.customerRequest.create).not.toHaveBeenCalled(); });
});
