import {beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({ctx:{accountId:'a1',userId:'u1',roleNames:['CUSTOMER_USER'],permissions:['portal.shipments.read'],dataMode:'DEMO'},scope:{isAllClients:false,authorizedClientIds:['target'],teamIds:[]},db:{shipment:{findFirst:vi.fn(),findUnique:vi.fn()}}}));
vi.mock('../../../packages/auth/src/auth',()=>({getAccountContext:async()=>m.ctx}));
vi.mock('../../../packages/auth/src/scope-engine',()=>({getEffectiveUserScope:async()=>m.scope}));
vi.mock('@qubere/auth',async()=>({...await import('../../../packages/auth/src/portal-auth'),getAccountContext:async()=>m.ctx,getEffectiveUserScope:async()=>m.scope}));
vi.mock('@qubere/db',async()=>({...await import('../../../packages/db/src/services/portal-status-mapper'),db:m.db,withAccountIdContext: (_account: unknown, fn: Function) => fn(), withDataModeContext:(_mode:unknown,fn:Function)=>fn(),isDataMode:()=>true}));
const route=await import('../src/app/api/shipments/[id]/answers/route');
const params={params:Promise.resolve({id:'s1'})};
beforeEach(()=>{vi.clearAllMocks();m.db.shipment.findFirst.mockResolvedValue({accountId:'a1',clientId:'target',importerName:'Target'});m.db.shipment.findUnique.mockResolvedValue({id:'s1',shipmentNumber:'SHP1',status:'In Progress',customsFilings:[],entryProofs:[],etaObservations:[],trackingEvents:[],legs:[],trackingIdentifiers:[],shipmentCharges:[],invoiceLines:[],customerRequests:[],complianceDeadlines:[],pgaHolds:[],demurrageExposureUsd:null,actualBuyCost:1234,expectedBuyCost:4321,grossProfit:222,grossMarginPct:50,humanNotes:'PRIVATE'})});
describe('Shipment answers HTTP scope and redaction',()=>{
 it('never reads shipment content for another client',async()=>{m.db.shipment.findFirst.mockResolvedValue({accountId:'a1',clientId:'amazon',importerName:'Amazon'});expect((await route.GET(new Request('http://portal/answers'),params)).status).toBe(404);expect(m.db.shipment.findUnique).not.toHaveBeenCalled()});
 it('returns an explicit safe projection even when ORM data contains internal costs',async()=>{const r=await route.GET(new Request('http://portal/answers'),params);expect(r.status).toBe(200);expect(r.headers.get('Cache-Control')).toBe('no-store');const content=JSON.stringify(await r.json());expect(content).not.toMatch(/actualBuyCost|expectedBuyCost|grossProfit|grossMarginPct|humanNotes|PRIVATE/);expect(m.db.shipment.findUnique).toHaveBeenCalledWith(expect.objectContaining({include:expect.objectContaining({invoiceLines:expect.objectContaining({where:{invoice:{accountId:'a1',clientId:'target'}}}),shipmentCharges:expect.objectContaining({where:{portalVisible:true}})})}))});
});
