/**
 * Comprehensive Field Inventory across existing extraction, UI, and storage paths.
 *
 * This is the ONE bridge table between the field-name vocabularies that the
 * document flow uses and that historically never translated to each other:
 *
 *  - `tradeMetadataKey`      camelCase key on `ShipmentDocument.extractedJson.tradeMetadata`
 *                            (what the shipment page + document viewer read)
 *  - `extractionSchemaKeys`  snake_case names from `extractionSchemas.ts`
 *                            (what `MISSING_EXTRACTION:*` exceptions are keyed on)
 *  - `reconciliationKey`     the `fieldKey` in `reconciliationRules.ts`
 *                            (what the cross-document reconciliation engine compares)
 *  - `canonicalKey`          the `CANONICAL_FIELD_REGISTRY_V1` key (materialization),
 *                            or an `annotation.*` sentinel for document-scoped fields
 *                            that have no shipment column
 *
 * `src/lib/documents/fieldDictionary.ts` exposes the lookups built from this table.
 *
 * Original drift keys documented in docs/plans/LLM-UNIVERSAL-FIELD-HYDRATION.md.
 */

import type { FieldInventoryItem } from "../types/canonicalRegistry";

const CI = "Commercial Invoice";
const PACK = "Packing List";
const BOL = "Bill of Lading";
const AWB = "Air Waybill";
const COO = "Certificate of Origin";
const ISF = "ISF";
const ENTRY = "Entry Summary";
const EUR1 = "EUR.1 Certificate";
const ATR = "A.TR Certificate";
const SEA_WB = "Sea Waybill";
const ARR_NOTICE = "Arrival Notice";
const CUST_ENTRY = "Customs Entry";
const DELIVERY_NOTE = "Delivery Note";
const SHIP_INSTR = "Shipping Instruction";
const CMR = "CMR Consignment Note";
const FWD_INSTR = "Forwarding Instruction";
const BOOKING_REQ = "Booking Request";
const PO = "Purchase Order";

export const FIELD_INVENTORY: FieldInventoryItem[] = [
  // ---------------------------------------------------------------------------
  // SHIPMENT SCALARS — materialized onto a Shipment column via the registry
  // ---------------------------------------------------------------------------
  {
    legacyKey: "carrier",
    tradeMetadataKey: "carrier",
    fieldReviewLabel: "Carrier",
    directShipmentColumn: "carrierName",
    factFieldName: "carrierName",
    canonicalKey: "shipment.carrier.name",
    entityKind: "SHIPMENT",
    isDriftKey: true,
    scope: "shipment",
    extractionSchemaKeys: ["carrier_name"],
    docTypes: [BOL, AWB, CI, DELIVERY_NOTE, CMR, ARR_NOTICE],
    notes:
      "Drift: tradeMetadata uses 'carrier', field-review map expects 'carrierName', Shipment column is 'carrierName'.",
  },
  {
    legacyKey: "originCountry",
    tradeMetadataKey: "originCountry",
    fieldReviewLabel: "Country of Origin",
    directShipmentColumn: "countryOfOrigin",
    factFieldName: "countryOfOrigin",
    canonicalKey: "shipment.originCountry",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["country_of_origin", "origin_country", "exporting_country"],
    reconciliationKey: "countryOfOrigin",
    docTypes: [CI, COO, PACK, ISF, EUR1, ATR],
    notes: "Mapped via dedicated originCountry handler in field-review route.",
  },
  {
    legacyKey: "destinationCountry",
    tradeMetadataKey: "destinationCountry",
    fieldReviewLabel: "Destination Country",
    directShipmentColumn: "destinationCountry",
    factFieldName: "destinationCountry",
    canonicalKey: "shipment.destinationCountry",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    docTypes: [CI, BOL],
  },
  {
    legacyKey: "countryOfExport",
    tradeMetadataKey: "countryOfExport",
    fieldReviewLabel: "Country of Export",
    directShipmentColumn: "countryOfExport",
    canonicalKey: "shipment.countryOfExport",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    docTypes: [CI],
    notes:
      "Distinct from destination. Historically the extractor aliased this to destinationCountry (finding #4).",
  },
  {
    legacyKey: "incoterm",
    tradeMetadataKey: "incoterm",
    fieldReviewLabel: "Incoterm",
    directShipmentColumn: "incoterm",
    factFieldName: "incoterm",
    canonicalKey: "shipment.incoterm",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["incoterm"],
    docTypes: [CI],
  },
  {
    legacyKey: "currency",
    tradeMetadataKey: "currency",
    fieldReviewLabel: "Invoice Currency",
    directShipmentColumn: "invoiceCurrency",
    factFieldName: "invoiceCurrency",
    canonicalKey: "shipment.financial.invoiceCurrency",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["currency"],
    reconciliationKey: "currency",
    docTypes: [CI],
  },
  {
    legacyKey: "invoiceNumber",
    tradeMetadataKey: "invoiceNumber",
    fieldReviewLabel: "Invoice Number",
    factFieldName: "invoiceNumber",
    canonicalKey: "shipment.invoiceNumber",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["invoice_number", "invoice_reference"],
    reconciliationKey: "invoiceNumber",
    docTypes: [CI, PACK, EUR1],
  },
  {
    legacyKey: "invoiceDate",
    tradeMetadataKey: "invoiceDate",
    fieldReviewLabel: "Invoice Date",
    factFieldName: "invoiceDate",
    canonicalKey: "shipment.invoiceDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["invoice_date"],
    docTypes: [CI],
  },
  {
    legacyKey: "invoiceSubtotal",
    tradeMetadataKey: "invoiceSubtotal",
    fieldReviewLabel: "Total Invoice Amount",
    factFieldName: "totalAmount",
    canonicalKey: "shipment.financial.invoiceSubtotal",
    entityKind: "SHIPMENT",
    isDriftKey: true,
    scope: "shipment",
    extractionSchemaKeys: ["total_value", "total_customs_value"],
    reconciliationKey: "totalValue",
    docTypes: [CI, CUST_ENTRY],
    notes:
      "Drift: extracted as 'invoiceSubtotal' or 'totalAmount', Fact uses 'totalAmount', no dedicated Shipment column.",
  },

  // ---------------------------------------------------------------------------
  // PARTIES — resolved to a ShipmentParty role
  // ---------------------------------------------------------------------------
  {
    legacyKey: "exporterName",
    tradeMetadataKey: "exporterName",
    fieldReviewLabel: "Exporter / Shipper",
    factFieldName: "exporterName",
    canonicalKey: "party.exporter.name",
    entityKind: "PARTY_ROLE",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["seller_name", "exporter_name", "shipper_name"],
    reconciliationKey: "shipperName",
    docTypes: [CI, COO, BOL, AWB, ISF, SHIP_INSTR, SEA_WB, FWD_INSTR, BOOKING_REQ, PO],
    notes: "Resolves EXPORTER party role via EntityResolutionService.",
  },
  {
    legacyKey: "importerName",
    tradeMetadataKey: "importerName",
    fieldReviewLabel: "Importer / Consignee",
    factFieldName: "importerName",
    canonicalKey: "party.importer.name",
    entityKind: "PARTY_ROLE",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["buyer_name", "consignee_name", "importer_name", "importer_of_record"],
    reconciliationKey: "consigneeName",
    docTypes: [CI, BOL, AWB, ISF, ENTRY, DELIVERY_NOTE, SHIP_INSTR, CMR, SEA_WB, ARR_NOTICE, FWD_INSTR, BOOKING_REQ, PO],
    notes: "Resolves IMPORTER_OF_RECORD party role via EntityResolutionService.",
  },
  {
    legacyKey: "notifyParty",
    tradeMetadataKey: "notifyParty",
    fieldReviewLabel: "Notify Party",
    canonicalKey: "annotation.notifyParty",
    entityKind: "PARTY_ROLE",
    isDriftKey: false,
    scope: "document",
    reconciliationKey: "notifyParty",
    docTypes: [BOL],
  },

  // ---------------------------------------------------------------------------
  // TRANSPORT / TRACKING — document-scoped: no Shipment column, annotation only
  // ---------------------------------------------------------------------------
  {
    legacyKey: "transportDocumentNumber",
    tradeMetadataKey: "transportDocumentNumber",
    fieldReviewLabel: "Bill of Lading Number",
    factFieldName: "billOfLading",
    canonicalKey: "tracking.billOfLading",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: true,
    scope: "document",
    extractionSchemaKeys: ["bl_number", "bol_or_awb_reference"],
    reconciliationKey: "billOfLadingNumber",
    docTypes: [BOL, ARR_NOTICE],
    notes: "Drift: extracted as 'transportDocumentNumber' or 'billOfLading'; TrackingMaterializer is a stub.",
  },
  {
    legacyKey: "airWaybill",
    tradeMetadataKey: "airWaybill",
    fieldReviewLabel: "Air Waybill Number",
    factFieldName: "airWaybill",
    canonicalKey: "tracking.airWaybill",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["awb_number"],
    docTypes: [AWB],
  },
  {
    legacyKey: "vesselName",
    tradeMetadataKey: "vesselName",
    fieldReviewLabel: "Vessel Name",
    canonicalKey: "annotation.vesselName",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["vessel_name"],
    docTypes: [BOL, SEA_WB],
  },
  {
    legacyKey: "voyageNumber",
    tradeMetadataKey: "voyageNumber",
    fieldReviewLabel: "Voyage Number",
    canonicalKey: "annotation.voyageNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["voyage"],
    docTypes: [BOL],
  },
  {
    legacyKey: "portOfLoading",
    tradeMetadataKey: "portOfLoading",
    fieldReviewLabel: "Port of Loading",
    canonicalKey: "annotation.portOfLoading",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["port_of_loading", "airport_of_origin"],
    docTypes: [BOL, AWB, SHIP_INSTR, SEA_WB, FWD_INSTR, BOOKING_REQ],
  },
  {
    legacyKey: "portOfDischarge",
    tradeMetadataKey: "portOfDischarge",
    fieldReviewLabel: "Port of Discharge",
    canonicalKey: "annotation.portOfDischarge",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["port_of_discharge", "airport_of_dest"],
    docTypes: [BOL, AWB, SHIP_INSTR, SEA_WB, FWD_INSTR, BOOKING_REQ],
  },
  {
    legacyKey: "containerNumber",
    tradeMetadataKey: "containerNumber",
    fieldReviewLabel: "Container Number",
    canonicalKey: "annotation.containerNumber",
    entityKind: "EQUIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["container_numbers"],
    reconciliationKey: "containerNumber",
    docTypes: [BOL, PACK],
  },
  {
    legacyKey: "onBoardDate",
    tradeMetadataKey: "onBoardDate",
    fieldReviewLabel: "On-Board Date",
    directShipmentColumn: "ladingDate",
    canonicalKey: "shipment.onBoardDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["on_board_date"],
    docTypes: [BOL, SEA_WB],
  },

  // ---------------------------------------------------------------------------
  // CARGO — weight / quantity / packaging
  // ---------------------------------------------------------------------------
  {
    legacyKey: "totalWeight",
    tradeMetadataKey: "totalWeight",
    fieldReviewLabel: "Gross Weight",
    factFieldName: "grossWeight",
    canonicalKey: "shipment.cargo.grossWeight",
    entityKind: "SHIPMENT",
    isDriftKey: true,
    scope: "document",
    extractionSchemaKeys: ["gross_weight"],
    reconciliationKey: "grossWeight",
    docTypes: [PACK, BOL, AWB, SEA_WB, ARR_NOTICE],
    notes: "Drift: tradeMetadata uses 'totalWeight', Fact uses 'grossWeight'. grossWeight column is not materializer-allowlisted → annotation scope.",
  },
  {
    legacyKey: "netWeight",
    tradeMetadataKey: "netWeight",
    fieldReviewLabel: "Net Weight",
    canonicalKey: "annotation.netWeight",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["net_weight"],
    reconciliationKey: "netWeight",
    docTypes: [PACK],
  },
  {
    legacyKey: "cartonCount",
    tradeMetadataKey: "cartonCount",
    fieldReviewLabel: "Carton Count",
    canonicalKey: "annotation.cartonCount",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["carton_count"],
    reconciliationKey: "packageCount",
    docTypes: [PACK, BOL],
  },
  {
    legacyKey: "totalQuantity",
    tradeMetadataKey: "totalQuantity",
    fieldReviewLabel: "Total Quantity",
    canonicalKey: "annotation.totalQuantity",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    reconciliationKey: "totalQuantity",
    docTypes: [CI, PACK, BOL, "CMR", CUST_ENTRY],
    notes: "Computed from the sum of extracted line-item quantities when the scalar is absent — this is what the invoice↔packing quantity reconciliation compares.",
  },

  // ---------------------------------------------------------------------------
  // LINE ITEMS
  // ---------------------------------------------------------------------------
  {
    legacyKey: "hsHtsCode",
    tradeMetadataKey: "hsHtsCode",
    fieldReviewLabel: "HTS Classification Code",
    factFieldName: "htsCode",
    canonicalKey: "lineItem[].htsCode",
    entityKind: "LINE_ITEM",
    isDriftKey: true,
    scope: "lineItem",
    extractionSchemaKeys: ["hs_code", "hs_6_code"],
    // No docTypes → excluded from per-document Field Review; HTS is reviewed
    // per line item in LineItemsTable, not per document (finding #3).
    docTypes: [],
    notes: "Drift: extracted as 'hsHtsCode', 'htsCode', or 'htsCandidate'; Fact uses 'htsCode'.",
  },
  { legacyKey: "lineNumber", factFieldName: "lineNumber", canonicalKey: "lineItem[].lineNumber", entityKind: "LINE_ITEM", isDriftKey: false, scope: "lineItem" },
  { legacyKey: "description", factFieldName: "description", canonicalKey: "lineItem[].description", entityKind: "LINE_ITEM", isDriftKey: false, scope: "lineItem" },
  { legacyKey: "quantity", factFieldName: "quantity", canonicalKey: "lineItem[].quantity", entityKind: "LINE_ITEM", isDriftKey: false, scope: "lineItem" },
  { legacyKey: "unitPrice", factFieldName: "unitPrice", canonicalKey: "lineItem[].unitPrice", entityKind: "LINE_ITEM", isDriftKey: false, scope: "lineItem" },

  // ---------------------------------------------------------------------------
  // FILING DRAFT & CUSTOMS
  // ---------------------------------------------------------------------------
  { legacyKey: "entryNumber", tradeMetadataKey: "entryNumber", factFieldName: "entryNumber", canonicalKey: "filing.entryNumber", entityKind: "FILING_DRAFT", isDriftKey: false, scope: "shipment", extractionSchemaKeys: ["entry_number"], docTypes: [CUST_ENTRY] },
  { legacyKey: "entryType", factFieldName: "entryType", canonicalKey: "filing.entryType", entityKind: "FILING_DRAFT", isDriftKey: false, scope: "shipment" },
  { legacyKey: "portOfEntry", tradeMetadataKey: "portOfEntry", factFieldName: "portOfEntry", canonicalKey: "filing.portOfEntry", entityKind: "FILING_DRAFT", isDriftKey: false, scope: "shipment", extractionSchemaKeys: ["port_of_entry"], docTypes: [CUST_ENTRY] },

  // ---------------------------------------------------------------------------
  // NEW DOCUMENT TYPES — Delivery Note / Shipping Instruction / CMR /
  // Sea Waybill / Arrival Notice / Customs Entry / EUR.1 / A.TR — document-
  // scoped, annotation-only fields (no reconciliation rule or Shipment column
  // assigned yet; see extractionSchemas.ts for the source field checklist).
  // ---------------------------------------------------------------------------
  {
    legacyKey: "deliveryNoteNumber",
    tradeMetadataKey: "deliveryNoteNumber",
    fieldReviewLabel: "Delivery Note Number",
    canonicalKey: "annotation.deliveryNoteNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["delivery_note_number"],
    docTypes: [DELIVERY_NOTE],
  },
  {
    legacyKey: "deliveryNoteDate",
    tradeMetadataKey: "deliveryNoteDate",
    fieldReviewLabel: "Delivery Note Date",
    canonicalKey: "annotation.deliveryNoteDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["delivery_note_date"],
    docTypes: [DELIVERY_NOTE],
  },
  {
    legacyKey: "deliveryLocation",
    tradeMetadataKey: "deliveryLocation",
    fieldReviewLabel: "Delivery Location",
    canonicalKey: "annotation.deliveryLocation",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["delivery_location"],
    docTypes: [DELIVERY_NOTE],
  },
  {
    legacyKey: "receivedBy",
    tradeMetadataKey: "receivedBy",
    fieldReviewLabel: "Received By",
    canonicalKey: "annotation.receivedBy",
    entityKind: "PARTY_ROLE",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["received_by"],
    docTypes: [DELIVERY_NOTE],
  },
  {
    legacyKey: "receivedDate",
    tradeMetadataKey: "receivedDate",
    fieldReviewLabel: "Received Date",
    canonicalKey: "annotation.receivedDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["received_date"],
    docTypes: [DELIVERY_NOTE],
  },
  {
    legacyKey: "instructionNumber",
    tradeMetadataKey: "instructionNumber",
    fieldReviewLabel: "Instruction Number",
    canonicalKey: "annotation.instructionNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["instruction_number"],
    docTypes: [SHIP_INSTR],
  },
  {
    legacyKey: "instructionDate",
    tradeMetadataKey: "instructionDate",
    fieldReviewLabel: "Instruction Date",
    canonicalKey: "annotation.instructionDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["instruction_date"],
    docTypes: [SHIP_INSTR, FWD_INSTR],
  },
  {
    legacyKey: "bookingNumber",
    tradeMetadataKey: "bookingNumber",
    fieldReviewLabel: "Booking Number",
    canonicalKey: "annotation.bookingNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["booking_number"],
    docTypes: [SHIP_INSTR, FWD_INSTR, BOOKING_REQ],
  },
  {
    legacyKey: "requestedSailingDate",
    tradeMetadataKey: "requestedSailingDate",
    fieldReviewLabel: "Requested Sailing Date",
    canonicalKey: "annotation.requestedSailingDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["requested_sailing_date"],
    docTypes: [SHIP_INSTR],
  },
  {
    legacyKey: "goodsDescription",
    tradeMetadataKey: "goodsDescription",
    fieldReviewLabel: "Description of Goods",
    canonicalKey: "annotation.goodsDescription",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["goods_description"],
    docTypes: [SHIP_INSTR, EUR1, ATR, COO, FWD_INSTR],
  },
  {
    legacyKey: "instructionReference",
    tradeMetadataKey: "instructionReference",
    fieldReviewLabel: "Instruction Reference",
    canonicalKey: "annotation.instructionReference",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["instruction_reference"],
    docTypes: [FWD_INSTR],
  },
  {
    legacyKey: "poNumber",
    tradeMetadataKey: "poNumber",
    fieldReviewLabel: "Purchase Order Number",
    canonicalKey: "annotation.poNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["po_number"],
    docTypes: [PO],
  },
  {
    legacyKey: "poDate",
    tradeMetadataKey: "poDate",
    fieldReviewLabel: "Purchase Order Date",
    canonicalKey: "annotation.poDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["po_date"],
    docTypes: [PO],
  },
  {
    legacyKey: "cmrNumber",
    tradeMetadataKey: "cmrNumber",
    fieldReviewLabel: "CMR Number",
    canonicalKey: "annotation.cmrNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["cmr_number"],
    docTypes: [CMR],
  },
  {
    legacyKey: "issueDate",
    tradeMetadataKey: "issueDate",
    fieldReviewLabel: "Issue Date",
    canonicalKey: "annotation.issueDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["issue_date"],
    docTypes: [CMR, EUR1, ATR],
  },
  {
    legacyKey: "senderName",
    tradeMetadataKey: "senderName",
    fieldReviewLabel: "Sender",
    canonicalKey: "annotation.senderName",
    entityKind: "PARTY_ROLE",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["sender_name"],
    docTypes: [CMR],
  },
  {
    legacyKey: "placeOfTakingOverGoods",
    tradeMetadataKey: "placeOfTakingOverGoods",
    fieldReviewLabel: "Place of Taking Over Goods",
    canonicalKey: "annotation.placeOfTakingOverGoods",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["place_of_taking_over_goods"],
    docTypes: [CMR],
  },
  {
    legacyKey: "placeOfDelivery",
    tradeMetadataKey: "placeOfDelivery",
    fieldReviewLabel: "Place of Delivery",
    canonicalKey: "annotation.placeOfDelivery",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["place_of_delivery"],
    docTypes: [CMR],
  },
  {
    legacyKey: "vehicleRegistration",
    tradeMetadataKey: "vehicleRegistration",
    fieldReviewLabel: "Vehicle Registration",
    canonicalKey: "annotation.vehicleRegistration",
    entityKind: "EQUIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["vehicle_registration"],
    docTypes: [CMR],
  },
  {
    legacyKey: "seaWaybillNumber",
    tradeMetadataKey: "seaWaybillNumber",
    fieldReviewLabel: "Sea Waybill Number",
    canonicalKey: "annotation.seaWaybillNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["sea_waybill_number"],
    docTypes: [SEA_WB],
  },
  {
    legacyKey: "arrivalNoticeNumber",
    tradeMetadataKey: "arrivalNoticeNumber",
    fieldReviewLabel: "Arrival Notice Number",
    canonicalKey: "annotation.arrivalNoticeNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["arrival_notice_number"],
    docTypes: [ARR_NOTICE],
  },
  {
    legacyKey: "noticeDate",
    tradeMetadataKey: "noticeDate",
    fieldReviewLabel: "Notice Date",
    canonicalKey: "annotation.noticeDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["notice_date"],
    docTypes: [ARR_NOTICE],
  },
  {
    legacyKey: "estimatedArrivalDate",
    tradeMetadataKey: "estimatedArrivalDate",
    fieldReviewLabel: "Estimated Arrival Date",
    directShipmentColumn: "estimatedArrival",
    canonicalKey: "shipment.estimatedArrivalDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["estimated_arrival_date"],
    docTypes: [ARR_NOTICE],
  },
  {
    legacyKey: "lastFreeDate",
    tradeMetadataKey: "lastFreeDate",
    fieldReviewLabel: "Last Free Date",
    directShipmentColumn: "lastFreeDay",
    canonicalKey: "shipment.lastFreeDate",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "shipment",
    extractionSchemaKeys: ["last_free_date"],
    docTypes: [ARR_NOTICE],
  },
  {
    legacyKey: "releaseStatus",
    tradeMetadataKey: "releaseStatus",
    fieldReviewLabel: "Release Status",
    canonicalKey: "annotation.releaseStatus",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["release_status"],
    docTypes: [ARR_NOTICE, CUST_ENTRY],
  },
  {
    legacyKey: "filingDate",
    tradeMetadataKey: "filingDate",
    fieldReviewLabel: "Filing Date",
    canonicalKey: "annotation.filingDate",
    entityKind: "FILING_DRAFT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["filing_date"],
    docTypes: [CUST_ENTRY],
  },
  {
    legacyKey: "totalDuty",
    tradeMetadataKey: "totalDuty",
    fieldReviewLabel: "Total Duty",
    canonicalKey: "annotation.totalDuty",
    entityKind: "FILING_DRAFT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["total_duty"],
    docTypes: [CUST_ENTRY],
  },
  {
    legacyKey: "totalTax",
    tradeMetadataKey: "totalTax",
    fieldReviewLabel: "Total Tax",
    canonicalKey: "annotation.totalTax",
    entityKind: "FILING_DRAFT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["total_tax"],
    docTypes: [CUST_ENTRY],
  },
  {
    legacyKey: "certificateNumber",
    tradeMetadataKey: "certificateNumber",
    fieldReviewLabel: "Certificate Number",
    canonicalKey: "annotation.certificateNumber",
    entityKind: "TRACKING_IDENTIFIER",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["certificate_number"],
    docTypes: [EUR1, ATR],
  },
  {
    legacyKey: "customsEndorsement",
    tradeMetadataKey: "customsEndorsement",
    fieldReviewLabel: "Customs Endorsement",
    canonicalKey: "annotation.customsEndorsement",
    entityKind: "SHIPMENT",
    isDriftKey: false,
    scope: "document",
    extractionSchemaKeys: ["customs_endorsement"],
    docTypes: [EUR1, ATR],
  },
];
