-- Generated from Prisma 6.19.3 migrate diff after applying the full migration history.
-- Adds indexes, foreign keys, and canonical index names required by schema.prisma.

CREATE UNIQUE INDEX "FilingUIConfig_country_procedureCode_messageName_messageTyp_key" ON "FilingUIConfig"("country", "procedureCode", "messageName", "messageType", "transactionType");
CREATE UNIQUE INDEX "FilingMasterDataSource_sourceName_key" ON "FilingMasterDataSource"("sourceName");
CREATE INDEX "FilingMasterDataSource_sourceName_idx" ON "FilingMasterDataSource"("sourceName");
CREATE INDEX "WorkMetricSnapshot_accountId_date_idx" ON "WorkMetricSnapshot"("accountId", "date");
CREATE INDEX "ControlEvidence_accountId_idx" ON "ControlEvidence"("accountId");
CREATE INDEX "DrawbackLot_accountId_htsCode_idx" ON "DrawbackLot"("accountId", "htsCode");
CREATE INDEX "DrawbackLot_exportDeadline_idx" ON "DrawbackLot"("exportDeadline");
CREATE UNIQUE INDEX "DrawbackClaimSequence_accountId_key" ON "DrawbackClaimSequence"("accountId");
CREATE INDEX "HtsPgaRequirement_htsNumber_idx" ON "HtsPgaRequirement"("htsNumber");
CREATE INDEX "HtsPgaRequirement_agencyCode_idx" ON "HtsPgaRequirement"("agencyCode");
CREATE UNIQUE INDEX "HtsPgaRequirement_htsNumber_agencyCode_key" ON "HtsPgaRequirement"("htsNumber", "agencyCode");
CREATE UNIQUE INDEX "BillingEventDefinition_eventCode_key" ON "BillingEventDefinition"("eventCode");
CREATE INDEX "BillingEventDefinition_accountId_idx" ON "BillingEventDefinition"("accountId");
CREATE INDEX "BillingEventDefinition_eventCode_idx" ON "BillingEventDefinition"("eventCode");
CREATE INDEX "RateCard_accountId_idx" ON "RateCard"("accountId");
CREATE INDEX "RateCard_clientId_idx" ON "RateCard"("clientId");
CREATE INDEX "RateCard_importerId_idx" ON "RateCard"("importerId");
CREATE INDEX "RateCardVersion_rateCardId_idx" ON "RateCardVersion"("rateCardId");
CREATE UNIQUE INDEX "RateCardVersion_rateCardId_version_key" ON "RateCardVersion"("rateCardId", "version");
CREATE INDEX "RateRule_rateCardVersionId_idx" ON "RateRule"("rateCardVersionId");
CREATE UNIQUE INDEX "RateRuleCapabilityMapping_rateRuleId_eventDefId_key" ON "RateRuleCapabilityMapping"("rateRuleId", "eventDefId");
CREATE INDEX "CostProfile_accountId_idx" ON "CostProfile"("accountId");
CREATE UNIQUE INDEX "UsageEvent_idempotencyKey_key" ON "UsageEvent"("idempotencyKey");
CREATE INDEX "UsageEvent_accountId_idx" ON "UsageEvent"("accountId");
CREATE INDEX "UsageEvent_shipmentId_idx" ON "UsageEvent"("shipmentId");
CREATE INDEX "UsageEvent_clientId_idx" ON "UsageEvent"("clientId");
CREATE INDEX "UsageEvent_occurredAt_idx" ON "UsageEvent"("occurredAt");
CREATE INDEX "UsageEvent_eventCode_idx" ON "UsageEvent"("eventCode");
CREATE INDEX "ShipmentCharge_accountId_idx" ON "ShipmentCharge"("accountId");
CREATE INDEX "ShipmentCharge_shipmentId_idx" ON "ShipmentCharge"("shipmentId");
CREATE INDEX "ShipmentCharge_status_idx" ON "ShipmentCharge"("status");
CREATE INDEX "ShipmentCost_accountId_idx" ON "ShipmentCost"("accountId");
CREATE INDEX "ShipmentCost_shipmentId_idx" ON "ShipmentCost"("shipmentId");
CREATE INDEX "ShipmentCost_costType_idx" ON "ShipmentCost"("costType");
CREATE INDEX "ChargeAdjustment_chargeId_idx" ON "ChargeAdjustment"("chargeId");
CREATE UNIQUE INDEX "Invoice_invoiceNumber_key" ON "Invoice"("invoiceNumber");
CREATE INDEX "Invoice_accountId_idx" ON "Invoice"("accountId");
CREATE INDEX "Invoice_clientId_idx" ON "Invoice"("clientId");
CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");
CREATE INDEX "Invoice_invoiceNumber_idx" ON "Invoice"("invoiceNumber");
CREATE INDEX "InvoiceLine_invoiceId_idx" ON "InvoiceLine"("invoiceId");
CREATE INDEX "InvoiceLine_shipmentId_idx" ON "InvoiceLine"("shipmentId");
CREATE INDEX "Payment_accountId_idx" ON "Payment"("accountId");
CREATE INDEX "Payment_invoiceId_idx" ON "Payment"("invoiceId");
CREATE INDEX "BillingException_accountId_idx" ON "BillingException"("accountId");
CREATE INDEX "BillingException_status_idx" ON "BillingException"("status");
CREATE INDEX "BillingException_type_idx" ON "BillingException"("type");
CREATE INDEX "AccountMemory_accountId_idx" ON "AccountMemory"("accountId");
CREATE INDEX "AccountMemory_accountId_type_idx" ON "AccountMemory"("accountId", "type");
CREATE INDEX "AccountMemory_accountId_subjectType_subjectId_idx" ON "AccountMemory"("accountId", "subjectType", "subjectId");
CREATE INDEX "AccountMemory_supersedesMemoryId_idx" ON "AccountMemory"("supersedesMemoryId");
CREATE INDEX "MemoryEvidence_accountId_idx" ON "MemoryEvidence"("accountId");
CREATE INDEX "MemoryEvidence_memoryId_idx" ON "MemoryEvidence"("memoryId");
CREATE INDEX "AuditLog_source_idx" ON "AuditLog"("source");
CREATE INDEX "HtsDutyRate_rateType_idx" ON "HtsDutyRate"("rateType");
CREATE INDEX "HtsDutyRate_caseNumber_idx" ON "HtsDutyRate"("caseNumber");
CREATE INDEX "ImporterOfRecord_clientId_idx" ON "ImporterOfRecord"("clientId");

ALTER TABLE "ShipmentDocument" ADD CONSTRAINT "ShipmentDocument_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PscAttachment" ADD CONSTRAINT "PscAttachment_pscId_fkey" FOREIGN KEY ("pscId") REFERENCES "PostSummaryCorrection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Protest" ADD CONSTRAINT "Protest_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Protest" ADD CONSTRAINT "Protest_linkedPscId_fkey" FOREIGN KEY ("linkedPscId") REFERENCES "PostSummaryCorrection"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProtestEntry" ADD CONSTRAINT "ProtestEntry_protestId_fkey" FOREIGN KEY ("protestId") REFERENCES "Protest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProtestEntry" ADD CONSTRAINT "ProtestEntry_filingId_fkey" FOREIGN KEY ("filingId") REFERENCES "CustomsFiling"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProtestAttachment" ADD CONSTRAINT "ProtestAttachment_protestId_fkey" FOREIGN KEY ("protestId") REFERENCES "Protest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProtestNote" ADD CONSTRAINT "ProtestNote_protestId_fkey" FOREIGN KEY ("protestId") REFERENCES "Protest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Party" ADD CONSTRAINT "Party_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WorkMetricSnapshot" ADD CONSTRAINT "WorkMetricSnapshot_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ControlEvidence" ADD CONSTRAINT "ControlEvidence_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DrawbackLot" ADD CONSTRAINT "DrawbackLot_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DrawbackClaimSequence" ADD CONSTRAINT "DrawbackClaimSequence_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BillingEventDefinition" ADD CONSTRAINT "BillingEventDefinition_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateCard" ADD CONSTRAINT "RateCard_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateCard" ADD CONSTRAINT "RateCard_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateCard" ADD CONSTRAINT "RateCard_importerId_fkey" FOREIGN KEY ("importerId") REFERENCES "ImporterOfRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateCardVersion" ADD CONSTRAINT "RateCardVersion_rateCardId_fkey" FOREIGN KEY ("rateCardId") REFERENCES "RateCard"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateRule" ADD CONSTRAINT "RateRule_rateCardVersionId_fkey" FOREIGN KEY ("rateCardVersionId") REFERENCES "RateCardVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateRuleCapabilityMapping" ADD CONSTRAINT "RateRuleCapabilityMapping_rateRuleId_fkey" FOREIGN KEY ("rateRuleId") REFERENCES "RateRule"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RateRuleCapabilityMapping" ADD CONSTRAINT "RateRuleCapabilityMapping_eventDefId_fkey" FOREIGN KEY ("eventDefId") REFERENCES "BillingEventDefinition"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CostProfile" ADD CONSTRAINT "CostProfile_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_eventCode_fkey" FOREIGN KEY ("eventCode") REFERENCES "BillingEventDefinition"("eventCode") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UsageEvent" ADD CONSTRAINT "UsageEvent_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_usageEventId_fkey" FOREIGN KEY ("usageEventId") REFERENCES "UsageEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_rateCardVersionId_fkey" FOREIGN KEY ("rateCardVersionId") REFERENCES "RateCardVersion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_rateRuleId_fkey" FOREIGN KEY ("rateRuleId") REFERENCES "RateRule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentCharge" ADD CONSTRAINT "ShipmentCharge_invoiceLineId_fkey" FOREIGN KEY ("invoiceLineId") REFERENCES "InvoiceLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentCost" ADD CONSTRAINT "ShipmentCost_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShipmentCost" ADD CONSTRAINT "ShipmentCost_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShipmentCost" ADD CONSTRAINT "ShipmentCost_usageEventId_fkey" FOREIGN KEY ("usageEventId") REFERENCES "UsageEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ChargeAdjustment" ADD CONSTRAINT "ChargeAdjustment_chargeId_fkey" FOREIGN KEY ("chargeId") REFERENCES "ShipmentCharge"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_importerId_fkey" FOREIGN KEY ("importerId") REFERENCES "ImporterOfRecord"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BillingException" ADD CONSTRAINT "BillingException_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BillingException" ADD CONSTRAINT "BillingException_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BillingException" ADD CONSTRAINT "BillingException_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AccountMemory" ADD CONSTRAINT "AccountMemory_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AccountMemory" ADD CONSTRAINT "AccountMemory_supersedesMemoryId_fkey" FOREIGN KEY ("supersedesMemoryId") REFERENCES "AccountMemory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MemoryEvidence" ADD CONSTRAINT "MemoryEvidence_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MemoryEvidence" ADD CONSTRAINT "MemoryEvidence_memoryId_fkey" FOREIGN KEY ("memoryId") REFERENCES "AccountMemory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER INDEX "FilingActionConfiguration_country_procedureCode_messageName_s_k" RENAME TO "FilingActionConfiguration_country_procedureCode_messageName_key";
ALTER INDEX "WtoTariffRate_reporterIso2_partnerIso2_hsCode6_tariffYear_rateT" RENAME TO "WtoTariffRate_reporterIso2_partnerIso2_hsCode6_tariffYear_r_key";
