import { generateSimplePdfBuffer } from "./pdfGenerator";
import type { FiveOhSixPayload } from "@/modules/onboarding/fiveOhSix.service";

const ENTITY_TYPE_LABELS: Record<string, string> = {
  US_CORPORATION: "03 – Corporation",
  LLC: "09 – LLC",
  PARTNERSHIP: "02 – Partnership",
  SOLE_PROPRIETORSHIP: "01 – Sole Proprietorship",
  FOREIGN: "05 – Other (Foreign Entity)",
};

export function buildFiveOhSixPdfBuffer(payload: FiveOhSixPayload, caseRef: string): Buffer {
  const addr = payload.physicalAddress;
  const fullAddress = [addr.line1, addr.city, addr.stateProvince, addr.postalCode, addr.country]
    .filter(Boolean)
    .join(", ");

  const mailingAddr = payload.mailingAddress
    ? [
        payload.mailingAddress.line1,
        payload.mailingAddress.city,
        payload.mailingAddress.stateProvince,
        payload.mailingAddress.postalCode,
        payload.mailingAddress.country,
      ]
        .filter(Boolean)
        .join(", ")
    : "Same as physical";

  const officerRows = payload.officers.map((o, i) => ({
    num: String(i + 1),
    name: o.name,
    title: o.title,
    ssnLast4: `***-**-${o.ssnLast4}`,
    dobLast4: o.dobLast4,
  }));

  return generateSimplePdfBuffer({
    title: "CBP Form 5106 — Create / Update Importer Identity Form",
    subtitle: `Case Ref: ${caseRef}  |  Action: ${payload.action}  |  Generated by Qubere`,
    metadata: {
      "Importer Number Type": payload.importerNumberType,
      "Importer Number": payload.importerNumber ?? "(CBP-assigned — pending)",
      "Program Indicator": payload.programIndicator,
      "Action Code": payload.action,
    },
    sections: [
      {
        heading: "Importer Identity",
        items: [
          { label: "Legal Name", value: payload.legalName },
          { label: "Trade / DBA Name", value: payload.tradeName ?? "—" },
          {
            label: "Legal Business Type",
            value: ENTITY_TYPE_LABELS[payload.entityType] ?? payload.entityType,
          },
          { label: "NAICS Code", value: payload.naicsCode ?? "—" },
          { label: "Related Business", value: payload.relatedBusiness ? "Yes" : "No" },
        ],
      },
      {
        heading: "Physical Address",
        items: [{ label: "Address", value: fullAddress }],
      },
      {
        heading: "Mailing Address",
        items: [{ label: "Address", value: mailingAddr }],
      },
      {
        heading: "Contact Information",
        items: [
          { label: "Contact Name", value: payload.contact.name },
          { label: "Phone", value: payload.contact.phone },
          { label: "Email", value: payload.contact.email },
        ],
      },
      ...(payload.residentAgent
        ? [
            {
              heading: "US Resident Agent (Non-Resident Importer)",
              items: [
                { label: "Name", value: payload.residentAgent.name },
                { label: "Address", value: payload.residentAgent.address },
                { label: "Phone", value: payload.residentAgent.phone },
              ],
            },
          ]
        : []),
    ],
    tables:
      officerRows.length > 0
        ? [
            {
              heading: "Principal Officers / Owners",
              columns: [
                { key: "num", label: "#", width: 30 },
                { key: "name", label: "Name", width: 160 },
                { key: "title", label: "Title", width: 130 },
                { key: "ssnLast4", label: "SSN (last 4)", width: 90 },
                { key: "dobLast4", label: "DOB (MMDD)", width: 90 },
              ],
              rows: officerRows,
            },
          ]
        : [],
  });
}
