'use client';
import {useEffect,useState} from 'react';
import type {EntryProofPayload} from '@qubere/entry-proof';
type Proof={id:string;version:number;status:string;payload:EntryProofPayload;internalFindings:{id:string;rule:string;recommendation:string}[]};
export function EntryProofPanel({filingId}:{filingId:string}) {
 const [proof,setProof]=useState<Proof|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const r=await fetch(`/api/broker/entries/${filingId}/proof`);if(r.status===404){setProof(null);return}if(!r.ok)throw new Error('Could not load proof');setProof(await r.json());}
 useEffect(()=>{load().catch(e=>setError(e.message))},[filingId]);
 async function act(action:'generate'|'publish'){setBusy(true);setError('');try{const r=await fetch(`/api/broker/entries/${filingId}/${action==='generate'?'proof/generate':'publish'}`,{method:'POST'});if(!r.ok){const d=await r.json();throw new Error(d.error||'Action failed')}await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 return <section className="rounded-xl border border-border bg-surface p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-lg">Entry Proof</h2><p className="text-sm text-ink-muted">Review the frozen customer payload before publishing.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>act('generate')} className="rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-50">{busy?'Working…':'Generate / refresh'}</button><button disabled={busy} onClick={()=>act('publish')} className="rounded-lg bg-brand text-white px-4 py-2 text-sm disabled:opacity-50">Publish to customer</button></div></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!proof?<p className="text-sm text-ink-muted">Generate a proof to review classifications, duty coverage, and customer-safe findings.</p>:<><div className="flex flex-wrap gap-6 text-sm"><strong>Version {proof.version} · {proof.status}</strong><span>Score {proof.payload.scorecard.scoreOverall} / 100</span><span>{proof.payload.scorecard.linesVerified} / {proof.payload.scorecard.linesTotal} lines verified</span><span>Duty and fees ${proof.payload.totals.dutyAndFeesUsd.toLocaleString()}</span></div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Line','Classification','Value','Duty','Review state'].map(h=><th key={h} className="p-3 border-b border-border">{h}</th>)}</tr></thead><tbody>{proof.payload.lines.map(l=><tr key={l.lineNumber}><td className="p-3">{l.lineNumber} · {l.description}</td><td className="p-3">{l.htsCode}<p className="text-xs text-ink-muted">{l.classificationStatus}</p></td><td className="p-3">${l.enteredValueUsd.toLocaleString()}</td><td className="p-3">${l.lineDutyTotalUsd.toLocaleString()}</td><td className="p-3">{l.verifyState}<p className="text-xs text-ink-muted max-w-sm">{l.verifyReason}</p></td></tr>)}</tbody></table></div><details><summary className="text-sm cursor-pointer">Provenance and published payload</summary><pre className="overflow-auto max-h-96 text-xs p-4 bg-black/5 mt-3">{JSON.stringify(proof.payload,null,2)}</pre></details>{proof.internalFindings?.length>0&&<details><summary className="text-sm cursor-pointer">Internal recommendations (broker only)</summary>{proof.internalFindings.map(f=><p key={f.id} className="text-sm mt-3"><strong>{f.rule}:</strong> {f.recommendation}</p>)}</details>}</>}</section>;
}
