steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - "build"
      - "--target=document-worker"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker:$SHORT_SHA"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker:latest"
      - "."
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - "push"
      - "--all-tags"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "qubere-document-worker-demo"
      - "--image=us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker:$SHORT_SHA"
      - "--region=us-west1"
      - "--project=$PROJECT_ID"
      - "--quiet"
images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker:$SHORT_SHA"
  - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/document-worker:latest"
options: { logging: CLOUD_LOGGING_ONLY }
