steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - "build"
      - "--target=customs-web"
      - "--build-arg=CUSTOMS_APP_URL=https://demo-clear.qubere.ai"
      - "--build-arg=NEXT_PUBLIC_APP_ENV=demo"
      - "--build-arg=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsucXViZXJlLmFpJA"
      - "--build-arg=GIT_COMMIT_SHA=$SHORT_SHA"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web:$SHORT_SHA"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web:latest"
      - "."
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - "push"
      - "--all-tags"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "qubere-customs-demo"
      - "--image=us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web:$SHORT_SHA"
      - "--region=us-west1"
      - "--project=$PROJECT_ID"
      - "--startup-probe-path=/api/health/live"
      - "--liveness-probe-path=/api/health/live"
      - "--quiet"
images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web:$SHORT_SHA"
  - "us-west1-docker.pkg.dev/$PROJECT_ID/qubere-demo/customs-web:latest"
options: { logging: CLOUD_LOGGING_ONLY }
