// CBP-assigned surety codes from the Department of the Treasury's Listing of
// Approved Sureties (Department Circular 570), as published August 1, 2025.
// Source: docs/plans/catair-source-docs/active_sureties_2025.xlsx

export interface SuretyEntry {
  code: string;
  name: string;
}

export const ACTIVE_SURETIES: SuretyEntry[] = [
  { code: "146", name: "ACE AMERICAN INSURANCE COMPANY" },
  { code: "16",  name: "ACSTAR INSURANCE COMPANY" },
  { code: "32",  name: "AEGIS SECURITY INSURANCE COMPANY" },
  { code: "13",  name: "ALLEGHENY CASUALTY COMPANY" },
  { code: "923", name: "ALLIED WORLD INSURANCE COMPANY" },
  { code: "36",  name: "AMERICAN ALTERNATIVE INS CORP" },
  { code: "37",  name: "AMERICAN CASUALTY CO READING PA" },
  { code: "300", name: "AMERICAN CONTRACTORS INDEMNITY" },
  { code: "69",  name: "AMERICAN HOME ASSURANCE COMPANY" },
  { code: "127", name: "AMERICAN SOUTHERN INSURANCE COMPANY" },
  { code: "107", name: "ANTILLES INSURANCE COMPANY" },
  { code: "118", name: "ARCH INSURANCE COMPANY" },
  { code: "44",  name: "ARCH REINSURANCE COMPANY" },
  { code: "110", name: "ARGONAUT INSURANCE CO" },
  { code: "887", name: "ASCOT SURETY AND CASUALTY CO" },
  { code: "52",  name: "ASPEN AMERICAN INSURANCE COMPANY" },
  { code: "128", name: "ATLANTIC SPECIALTY INSURANCE" },
  { code: "692", name: "AXIS INSURANCE COMPANY" },
  { code: "130", name: "BANKERS INSURANCE GROUP" },
  { code: "611", name: "BERKLEY INSURANCE COMPANY" },
  { code: "46",  name: "BERKLEY REGIONAL INSURANCE CO" },
  { code: "76",  name: "BERKSHIRE HATHAWAY SPECIALTY INSURANCE COMPANY" },
  { code: "140", name: "BOND SAFEGUARD INSURANCE COMPANY" },
  { code: "157", name: "CAPITOL INDEMNITY CORPORATION" },
  { code: "160", name: "CAROLINA CASUALTY INSURANCE CO." },
  { code: "948", name: "CENTENNIAL CASUALTY COMPANY" },
  { code: "175", name: "CENTURY SURETY COMPANY" },
  { code: "186", name: "CHEROKEE INSURANCE CO" },
  { code: "181", name: "CINCINNATI INSURANCE COMPANY" },
  { code: "191", name: "CITIZENS INSURANCE CO OF AMERICA" },
  { code: "280", name: "COLONIAL AMERICAN CASUALTY AND" },
  { code: "188", name: "COLONIAL SURETY COMPANY" },
  { code: "213", name: "CONTINENTAL CASUALTY COMPANY" },
  { code: "244", name: "CONTINENTAL HERITAGE INSURANCE COMPANY" },
  { code: "217", name: "CONTINENTAL INSURANCE COMPANY" },
  { code: "215", name: "CONTRACTORS BONDING & INS.CO." },
  { code: "220", name: "COOPERATIVA DE SEGUROS MULTIPLES" },
  { code: "179", name: "COREPOINTE INSURANCE COMPANY" },
  { code: "789", name: "DEVELOPERS SURETY & INDEMNITY CO" },
  { code: "249", name: "EMPLOYERS INSURANCE CO OF WAUSAU" },
  { code: "80",  name: "ENDURANCE AMERICAN INSURANCE COMPANY" },
  { code: "440", name: "ENDURANCE REINSURANCE CORP OF AM" },
  { code: "676", name: "EULER HERMES NORTH AMERICA INS CO." },
  { code: "699", name: "EVEREST REINSURANCE COMPANY" },
  { code: "254", name: "EVERGREEN NATIONAL INDEMNITY CO." },
  { code: "264", name: "FARMINGTON CASUALTY COMPANY" },
  { code: "269", name: "FEDERAL INSURANCE COMPANY" },
  { code: "281", name: "FIDELITY AND DEPOSIT CO OF MD" },
  { code: "285", name: "FIREMAN'S FUND INSURANCE CO." },
  { code: "653", name: "FIRST FOUNDERS ASSURANCE COMPANY" },
  { code: "293", name: "FIRST INS CO OF HAWAII, LTD." },
  { code: "309", name: "GENERAL REINSURANCE CORP" },
  { code: "324", name: "GRANITE RE, INC." },
  { code: "35",  name: "GREAT AMERICAN ALLIANCE INS CO" },
  { code: "329", name: "GREAT AMERICAN INS CO" },
  { code: "097", name: "GREAT AMERINCA INS CO OF NY" },
  { code: "345", name: "GREAT MIDWEST INSURANCE COMPANY" },
  { code: "119", name: "GUARANTEE COMPANY OF NORTH AMERICA USA (THE)" },
  { code: "353", name: "HANOVER INSURANCE COMPANY" },
  { code: "360", name: "HARCO NATIONAL INSURANCE CO." },
  { code: "361", name: "HARTFORD ACCIDENT & INDEMNITY CO" },
  { code: "185", name: "HARTFORD CASUALTY INSURANCE CO" },
  { code: "365", name: "HARTFORD FIRE INSURANCE CO" },
  { code: "367", name: "HARTFORD INS CO. OF THE MIDWEST" },
  { code: "388", name: "HUDSON INSURANCE CO." },
  { code: "398", name: "IMT INSURANCE COMPANY" },
  { code: "464", name: "INDEMNITY NATIONAL INSURANCE COMPANY" },
  { code: "402", name: "INDIANA LUMBERMENS MUTUAL INS CO" },
  { code: "417", name: "INSURANCE CO OF THE STATE OF PA." },
  { code: "411", name: "INSURANCE COMPANY OF THE WEST" },
  { code: "421", name: "INTERNATIONAL FIDELITY INS CO" },
  { code: "55",  name: "IRONSHORE INDEMNITY INC." },
  { code: "435", name: "ISLAND INSURANCE COMPANY LTD." },
  { code: "538", name: "JET INSURANCE COMPANY" },
  { code: "462", name: "LEXINGTON NATIONAL INSURANCE COMPANY" },
  { code: "856", name: "LEXON INSURANCE COMPANY" },
  { code: "457", name: "LIBERTY MUTUAL INSURANCE CO" },
  { code: "642", name: "MARKEL INSURANCE COMPANY" },
  { code: "481", name: "MASSACHUSETTS BAY INSURANCE CO." },
  { code: "485", name: "MERCHANTS BONDING CO. (MUTUAL)" },
  { code: "497", name: "MID-CENTURY INSURANCE COMPANY" },
  { code: "672", name: "MUNICH REINSURANCE AMERICA" },
  { code: "528", name: "NATIONAL AMERICAN INSURANCE CO." },
  { code: "915", name: "NATIONAL CASUALTY COMPANY" },
  { code: "541", name: "NATIONAL FIRE INS CO OF HARTFORD" },
  { code: "549", name: "NATIONAL INDEMNITY COMPANY" },
  { code: "565", name: "NATIONAL UNION FIRE INSURANCE COMPANY OF PITTSBURGH, PA" },
  { code: "573", name: "NATIONWIDE MUTUAL INSURANCE CO." },
  { code: "50",  name: "NAVIGATORS INSURANCE CO." },
  { code: "577", name: "NEW HAMPSHIRE INSURANCE COMPANY" },
  { code: "664", name: "NEW YORK MARINE AND GENERAL INSURANCE COMPANY" },
  { code: "545", name: "NGM INSURANCE CO" },
  { code: "615", name: "NOVA CASUALTY COMPANY" },
  { code: "621", name: "OHIO CASUALTY INSURANCE CO." },
  { code: "625", name: "OHIO FARMERS INSURANCE COMPANY" },
  { code: "614", name: "OLD DOMINION INSURANCE COMPANY" },
  { code: "627", name: "OLD REPUBLIC INSURANCE CO." },
  { code: "616", name: "OLD REPUBLIC SURETY COMPANY" },
  { code: "645", name: "PACIFIC INDEMNITY COMPANY" },
  { code: "666", name: "PENNSYLVANIA INSURANCE COMPANY" },
  { code: "677", name: "PENNSYLVANIA NATIONAL MUTUAL" },
  { code: "120", name: "PHILADELPHIA INDEMNITY INSURANCE" },
  { code: "156", name: "PLATTE RIVER INSURANCE COMPANY" },
  { code: "697", name: "PROTECTIVE INSURANCE COMPANY" },
  { code: "95",  name: "QBE INSURANCE CORPORATION" },
  { code: "732", name: "RLI INSURANCE COMPANY" },
  { code: "741", name: "SAFECO INSURANCE CO. OF AMERICA" },
  { code: "738", name: "SAFETY NATIONAL CASUALTY CORP" },
  { code: "766", name: "SELECTIVE INSURANCE CO. OF AMERICA" },
  { code: "760", name: "SENECA INSURANCE COMPANY, INC." },
  { code: "445", name: "SENTRY SELECT INSURANCE COMPANY" },
  { code: "764", name: "SERVICE INSUREANCE COMPNAY INC. (THE)" },
  { code: "292", name: "SIRIUS AMERICA INSURANCE COMPANY" },
  { code: "54",  name: "SOUTHWEST MARINE AND GENERAL INSURANCE CO" },
  { code: "749", name: "ST PAUL FIRE AND MARINE INS CO" },
  { code: "751", name: "ST. PAUL MERCURY INSURANCE CO." },
  { code: "779", name: "STAR INSURANCE COMPANY" },
  { code: "781", name: "STATE AUTOMOBILE MUTUAL INS CO" },
  { code: "785", name: "STATE FARM FIRE & CASUALTY CO." },
  { code: "808", name: "SURETEC INSURANCE CO" },
  { code: "229", name: "SWISS RE CORPORATE SOLUTIONS AMERICA INSURANCE CORPORATION" },
  { code: "891", name: "SWISS RE CORPORATE SOLUTIONS PREMIER INSURANCE CORPORATION" },
  { code: "593", name: "SWISS REINSURANCE AMERICA CORP" },
  { code: "119", name: "THE GUARANTEE CO OF NO AMERICA" },
  { code: "056", name: "TRANSATLANTIC REINSURANCE COMPANY" },
  { code: "23",  name: "TRAVELERS CASUALTY & SURETY CO" },
  { code: "1",   name: "TRAVELERS CASUALTY AND SURETY CO" },
  { code: "4",   name: "TRAVELERS CASUALTY INSURANCE CO." },
  { code: "841", name: "TRAVELERS INDEMNITY COMPANY (THE)" },
  { code: "846", name: "U.S. SPECIALTY INSURANCE COMPANY" },
  { code: "861", name: "UNITED CASUALTY & SURETY INS CO" },
  { code: "870", name: "UNITED FIRE & CASUALTY COMPANY" },
  { code: "869", name: "UNITED STATES FIDELITY AND GUARANTY COMPANY" },
  { code: "873", name: "UNITED STATES FIRE INSURANCE COMPANY" },
  { code: "871", name: "UNITED STATES SURETY COMPNAY" },
  { code: "872", name: "UNITED SURETY AND INDEMNITY COMPANY" },
  { code: "594", name: "UNIVERSAL FIRE & CASUALTY INSURANCE COMPANY" },
  { code: "877", name: "UNIVERSAL SURETY COMPANY" },
  { code: "881", name: "UTICA MUTUAL INSURANCE COMPANY" },
  { code: "889", name: "VIGILANT INSURANCE COMPANY" },
  { code: "897", name: "WESTCHESTER FIRE INSURANCE CO." },
  { code: "913", name: "WESTERN SURETY COMPANY" },
  { code: "809", name: "WESTFIELD INSURANCE COMPANY" },
  { code: "810", name: "WESTFIELD NATIONAL INSURANCE COMPANY" },
  { code: "922", name: "WESTPORT INSURANCE CORPORATION" },
  { code: "530", name: "XL REINSURANCE AMERICA INC" },
  { code: "86",  name: "XL SPECIALTY INSURANCE COMPANY" },
  { code: "945", name: "ZURICH AMERICAN INSURANCE CO." },
];

const BY_CODE = new Map(ACTIVE_SURETIES.map((s) => [s.code.trim(), s]));
const BY_NAME = new Map(ACTIVE_SURETIES.map((s) => [s.name.trim().toUpperCase(), s]));

export function lookupSuretyByCode(code: string): SuretyEntry | undefined {
  return BY_CODE.get(code.trim().replace(/^0+/, "") ) ??
         BY_CODE.get(code.trim());
}

export function lookupSuretyByName(name: string): SuretyEntry | undefined {
  return BY_NAME.get(name.trim().toUpperCase());
}

export function isSuretyCodeValid(code: string): boolean {
  return lookupSuretyByCode(code) !== undefined;
}
