/**
 * Canonical Field Registry Release V1 (1.0.0)
 *
 * Immutable, governed definition catalog of canonical semantic fields
 * understood by Qubere's universal field hydration engine.
 */

import type { CanonicalFieldDefinition } from "../types/canonicalRegistry";

export const REGISTRY_VERSION_V1 = "1.0.0";

export const CANONICAL_FIELD_REGISTRY_V1: Record<string, CanonicalFieldDefinition> = {
  // ---------------------------------------------------------------------------
  // SHIPMENT ENTITY FIELDS
  // ---------------------------------------------------------------------------
  "shipment.carrier.name": {
    key: "shipment.carrier.name",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Carrier Name",
    description: "Legal or trade name of the ocean, air, or motor carrier transporting the cargo.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["carrier", "carrierName", "transportCarrier", "shippingLine", "airline"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "BILL_OF_LADING", "AIR_WAYBILL", "CARRIER_INVOICE"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "partyNameNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "carrierName" },
  },

  "shipment.incoterm": {
    key: "shipment.incoterm",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Incoterm",
    description: "Standard 3-letter Incoterms rule governing transport responsibilities (e.g. FOB, CIF, DDP).",
    dataType: "CODE",
    cardinality: "ONE",
    aliases: ["incoterm", "termsOfSale", "deliveryTerms", "tradeTerms"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "ENTRY_SUMMARY", "ISF"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "uppercaseCodeNormalizer",
    validators: ["isoIncotermValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "incoterm" },
  },

  "shipment.originCountry": {
    key: "shipment.originCountry",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Country of Origin",
    description: "ISO-2 country code representing the country of manufacture or primary origin.",
    dataType: "COUNTRY",
    cardinality: "ONE",
    aliases: ["originCountry", "countryOfOrigin", "coo", "origin"],
    sourceDocumentTypes: [
      "COMMERCIAL_INVOICE",
      "CERTIFICATE_OF_ORIGIN",
      "PACKING_LIST",
      "ENTRY_SUMMARY",
    ],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "isoCountryNormalizer",
    validators: ["iso2CountryValidator"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "REQUIRES_HIGH_CONFIDENCE_OR_CORROBORATION",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "countryOfOrigin" },
  },

  "shipment.destinationCountry": {
    key: "shipment.destinationCountry",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Destination Country",
    description: "ISO-2 country code representing final destination for customs clearance.",
    dataType: "COUNTRY",
    cardinality: "ONE",
    aliases: ["destinationCountry", "countryOfDestination", "finalDestination"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "BILL_OF_LADING", "AIR_WAYBILL", "ENTRY_SUMMARY", "ISF"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "isoCountryNormalizer",
    validators: ["iso2CountryValidator"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "EXPLICIT_SOURCE_POLICY_ONLY",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "destinationCountry" },
  },

  "shipment.invoiceNumber": {
    key: "shipment.invoiceNumber",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Invoice Number",
    description: "Commercial or seller invoice identifier.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["invoiceNumber", "invNo", "invoiceNo", "commercialInvoiceNo"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "cleanStringNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "invoiceNumber" },
  },

  "shipment.invoiceDate": {
    key: "shipment.invoiceDate",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Invoice Date",
    description: "ISO format date when the commercial invoice was issued.",
    dataType: "DATE",
    cardinality: "ONE",
    aliases: ["invoiceDate", "invDate", "dateOfInvoice"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "isoDateNormalizer",
    validators: ["isoDateValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "invoiceDate" },
  },

  "shipment.financial.invoiceCurrency": {
    key: "shipment.financial.invoiceCurrency",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Invoice Currency",
    description: "ISO-3 currency code (e.g. USD, EUR, JPY) of the commercial invoice.",
    dataType: "CURRENCY",
    cardinality: "ONE",
    aliases: ["currency", "invoiceCurrency", "curr"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "uppercaseCodeNormalizer",
    validators: ["isoCurrencyValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "invoiceCurrency" },
  },

  "shipment.financial.invoiceSubtotal": {
    key: "shipment.financial.invoiceSubtotal",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Total Invoice Amount",
    description: "Total monetary value of the invoice before extra charges or taxes.",
    dataType: "DECIMAL",
    cardinality: "ONE",
    aliases: ["invoiceSubtotal", "totalAmount", "totalInvoiceValue", "invoiceTotal"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "decimalMoneyNormalizer",
    validators: ["positiveDecimalValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "FactOnlyMaterializer",
    materializerConfig: { factField: "invoiceSubtotal" },
  },

  "shipment.cargo.grossWeight": {
    key: "shipment.cargo.grossWeight",
    version: REGISTRY_VERSION_V1,
    entityKind: "SHIPMENT",
    label: "Gross Weight",
    description: "Total gross weight of cargo including packaging.",
    dataType: "DECIMAL",
    cardinality: "ONE",
    aliases: ["totalWeight", "grossWeight", "totalGrossWeight"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "BILL_OF_LADING", "AIR_WAYBILL"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: null,
    normalizer: "decimalNumberNormalizer",
    validators: ["positiveDecimalValidator"],
    riskClass: "LOW",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "FactOnlyMaterializer",
    materializerConfig: { factField: "grossWeight" },
  },

  // ---------------------------------------------------------------------------
  // PARTY ROLE ENTITY FIELDS
  // ---------------------------------------------------------------------------
  "party.exporter.name": {
    key: "party.exporter.name",
    version: REGISTRY_VERSION_V1,
    entityKind: "PARTY_ROLE",
    label: "Exporter Name",
    description: "Name of the exporting legal entity or seller.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["exporterName", "exporter", "shipperName", "sellerName"],
    sourceDocumentTypes: [
      "COMMERCIAL_INVOICE",
      "PACKING_LIST",
      "CERTIFICATE_OF_ORIGIN",
      "ENTRY_SUMMARY",
      "ISF",
    ],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "partyNameNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "REQUIRES_ENTITY_RESOLUTION",
    materializer: "PartyRoleMaterializer",
    materializerConfig: { role: "EXPORTER" },
  },

  "party.importer.name": {
    key: "party.importer.name",
    version: REGISTRY_VERSION_V1,
    entityKind: "PARTY_ROLE",
    label: "Importer of Record Name",
    description: "Legal entity accountable for customs entry clearance and duties.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["importerName", "importerOfRecord", "ior", "consigneeName"],
    sourceDocumentTypes: [
      "COMMERCIAL_INVOICE",
      "BILL_OF_LADING",
      "AIR_WAYBILL",
      "ENTRY_SUMMARY",
      "ISF",
    ],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "ALWAYS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "partyNameNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "REQUIRES_ENTITY_RESOLUTION",
    materializer: "PartyRoleMaterializer",
    materializerConfig: { role: "IMPORTER_OF_RECORD" },
  },

  // ---------------------------------------------------------------------------
  // LINE ITEM ENTITY FIELDS
  // ---------------------------------------------------------------------------
  "lineItem[].lineNumber": {
    key: "lineItem[].lineNumber",
    version: REGISTRY_VERSION_V1,
    entityKind: "LINE_ITEM",
    label: "Line Item Number",
    description: "Sequence index of the item within invoice/packing list.",
    dataType: "INTEGER",
    cardinality: "MANY",
    aliases: ["lineNumber", "lineNo", "itemNo"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "HAS_LINE_ITEMS",
    requiredRule: null,
    normalizer: "integerNormalizer",
    validators: ["positiveIntegerValidator"],
    riskClass: "LOW",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "LineItemMaterializer",
    materializerConfig: { column: "lineNumber" },
  },

  "lineItem[].description": {
    key: "lineItem[].description",
    version: REGISTRY_VERSION_V1,
    entityKind: "LINE_ITEM",
    label: "Goods Description",
    description: "Detailed commercial or tariff description of the item.",
    dataType: "STRING",
    cardinality: "MANY",
    aliases: ["description", "goodsDescription", "itemDescription", "productDescription"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "HAS_LINE_ITEMS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "cleanStringNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "LineItemMaterializer",
    materializerConfig: { column: "description" },
  },

  "lineItem[].quantity": {
    key: "lineItem[].quantity",
    version: REGISTRY_VERSION_V1,
    entityKind: "LINE_ITEM",
    label: "Item Quantity",
    description: "Number of units for the line item.",
    dataType: "DECIMAL",
    cardinality: "MANY",
    aliases: ["quantity", "qty", "pieceCount"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "HAS_LINE_ITEMS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "decimalNumberNormalizer",
    validators: ["positiveDecimalValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "LineItemMaterializer",
    materializerConfig: { column: "quantity" },
  },

  "lineItem[].unitPrice": {
    key: "lineItem[].unitPrice",
    version: REGISTRY_VERSION_V1,
    entityKind: "LINE_ITEM",
    label: "Unit Price",
    description: "Price per single unit of item.",
    dataType: "DECIMAL",
    cardinality: "MANY",
    aliases: ["unitPrice", "price", "rate"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "ENTRY_SUMMARY"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "HAS_LINE_ITEMS",
    requiredRule: null,
    normalizer: "decimalMoneyNormalizer",
    validators: ["positiveDecimalValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "LineItemMaterializer",
    materializerConfig: { column: "unitPrice" },
  },

  "lineItem[].htsCode": {
    key: "lineItem[].htsCode",
    version: REGISTRY_VERSION_V1,
    entityKind: "LINE_ITEM",
    label: "HTS Code",
    description: "Harmonized Tariff Schedule classification (6 to 10 digits).",
    dataType: "CODE",
    cardinality: "MANY",
    aliases: ["htsCode", "hsHtsCode", "hsCode", "htsCandidate", "tariffSubheading"],
    sourceDocumentTypes: ["COMMERCIAL_INVOICE", "CERTIFICATE_OF_ORIGIN", "ENTRY_SUMMARY"],
    products: ["CUSTOMS"],
    jurisdictions: ["*"],
    applicabilityRule: "HAS_LINE_ITEMS",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "htsCodeNormalizer",
    validators: ["htsCodeStructureValidator"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "REQUIRES_HIGH_CONFIDENCE_OR_REVIEW",
    materializer: "LineItemMaterializer",
    materializerConfig: { column: "htsCode" },
  },

  // ---------------------------------------------------------------------------
  // TRACKING IDENTIFIERS
  // ---------------------------------------------------------------------------
  "tracking.billOfLading": {
    key: "tracking.billOfLading",
    version: REGISTRY_VERSION_V1,
    entityKind: "TRACKING_IDENTIFIER",
    label: "Bill of Lading",
    description: "Master or House Ocean Bill of Lading number.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["billOfLading", "transportDocumentNumber", "bolNumber", "mbl", "hbl"],
    sourceDocumentTypes: ["BILL_OF_LADING", "ENTRY_SUMMARY", "ISF", "COMMERCIAL_INVOICE"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "OCEAN_SHIPMENT",
    requiredRule: "OCEAN_FILING_REQUIRED",
    normalizer: "cleanIdentifierNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "TrackingMaterializer",
    materializerConfig: { identifierType: "MBL" },
  },

  "tracking.airWaybill": {
    key: "tracking.airWaybill",
    version: REGISTRY_VERSION_V1,
    entityKind: "TRACKING_IDENTIFIER",
    label: "Air Waybill",
    description: "Master or House Air Waybill number.",
    dataType: "STRING",
    cardinality: "ONE",
    aliases: ["airWaybill", "awbNumber", "mawb", "hawb"],
    sourceDocumentTypes: ["AIR_WAYBILL", "ENTRY_SUMMARY", "COMMERCIAL_INVOICE"],
    products: ["CUSTOMS", "TMS"],
    jurisdictions: ["*"],
    applicabilityRule: "AIR_SHIPMENT",
    requiredRule: "AIR_FILING_REQUIRED",
    normalizer: "cleanIdentifierNormalizer",
    validators: ["nonEmptyString"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "AUTO_IF_UNCONTRADICTED",
    materializer: "TrackingMaterializer",
    materializerConfig: { identifierType: "MAWB" },
  },

  // ---------------------------------------------------------------------------
  // FILING DRAFT ENTITY FIELDS
  // ---------------------------------------------------------------------------
  "filing.entryNumber": {
    key: "filing.entryNumber",
    version: REGISTRY_VERSION_V1,
    entityKind: "FILING_DRAFT",
    label: "CBP Entry Number",
    description: "11-character CBP entry number (filer code + entry identifier + check digit).",
    dataType: "CODE",
    cardinality: "ONE",
    aliases: ["entryNumber", "cbpEntryNumber"],
    sourceDocumentTypes: ["ENTRY_SUMMARY"],
    products: ["CUSTOMS"],
    jurisdictions: ["US"],
    applicabilityRule: "CUSTOMS_ENTRY",
    requiredRule: null,
    normalizer: "uppercaseCodeNormalizer",
    validators: ["cbpEntryNumberValidator"],
    riskClass: "CONSEQUENTIAL",
    promotionPolicy: "EXPLICIT_SOURCE_POLICY_ONLY",
    materializer: "FilingDraftMaterializer",
    materializerConfig: { draftField: "entryNumber" },
  },

  "filing.portOfEntry": {
    key: "filing.portOfEntry",
    version: REGISTRY_VERSION_V1,
    entityKind: "FILING_DRAFT",
    label: "Port of Entry",
    description: "4-digit Schedule D customs port code.",
    dataType: "CODE",
    cardinality: "ONE",
    aliases: ["portOfEntry", "entryPort", "portCode"],
    sourceDocumentTypes: ["ENTRY_SUMMARY", "ISF", "BILL_OF_LADING", "AIR_WAYBILL"],
    products: ["CUSTOMS"],
    jurisdictions: ["US"],
    applicabilityRule: "CUSTOMS_ENTRY",
    requiredRule: "CUSTOMS_FILING_REQUIRED",
    normalizer: "scheduleDPortNormalizer",
    validators: ["scheduleDPortValidator"],
    riskClass: "MEDIUM",
    promotionPolicy: "AUTO_IF_VALIDATED",
    materializer: "ShipmentScalarMaterializer",
    materializerConfig: { targetColumn: "portOfEntry" },
  },
};
