import {describe,it,expect} from 'vitest';
import {assembleShipmentAnswers,type ShipmentAnswersInput} from './shipmentAnswers';
const input=():ShipmentAnswersInput=>({id:'s1',shipmentNumber:'SHP-1',generatedAt:'2026-09-02T00:00:00Z',transportationStatus:'In transit',customsStatus:'Filed with customs',promiseState:null,healthLabel:null,carrierName:null,portOfEntry:null,estimatedArrival:null,lastFreeDay:null,demurrageExposureUsd:null,proofs:[],charges:[],invoices:[],milestones:[],referenceNumbers:[],requests:[],deadlines:[],holds:[]});
describe('deterministic shipment answers',()=>{
 it('keeps unavailable cost and clearance timing explicitly unknown',()=>{const a=assembleShipmentAnswers(input());expect(a.cost.estimatedTotalUsd).toBeNull();expect(a.cost.costIsPartial).toBe(true);expect(a.cards.find(c=>c.key==='clearance')?.status).toBe('UNKNOWN')});
 it('does not double count invoice totals or expose draft invoices and private charges',()=>{const i=input();i.proofs=[{dutyAndFeesUsd:0.1,complete:true}];i.charges=[{netAmount:0.2,currency:'USD',portalVisible:true,status:'RATED'},{netAmount:999,currency:'USD',portalVisible:false,status:'RATED'}];i.invoices=[{id:'i1',number:'INV',status:'SENT',total:0.3,currency:'USD'},{id:'draft',number:'SECRET',status:'DRAFT',total:900,currency:'USD'}];const a=assembleShipmentAnswers(i);expect(a.cost.estimatedTotalUsd).toBe(0.3);expect(a.cost.invoices).toHaveLength(1);expect(JSON.stringify(a)).not.toContain('SECRET')});
 it('marks incomplete proof and non-USD cost partial instead of silently converting',()=>{const i=input();i.proofs=[{dutyAndFeesUsd:50,complete:false}];i.charges=[{netAmount:100,currency:'EUR',portalVisible:true,status:'RATED'}];const a=assembleShipmentAnswers(i);expect(a.cost).toMatchObject({estimatedTotalUsd:50,brokerChargesUsd:null,costIsPartial:true})});
 it('exposes only explicitly customer-actionable open deadlines',()=>{const i=input();i.deadlines=[{id:'private',customerActionable:false,customerLabel:'INTERNAL',status:'OPEN',dueAt:null},{id:'closed',customerActionable:true,customerLabel:'Finished',status:'SATISFIED',dueAt:null},{id:'visible',customerActionable:true,customerLabel:'Upload invoice',status:'OPEN',dueAt:null}];const a=assembleShipmentAnswers(i);expect(a.needsFromYou.map(n=>n.id)).toEqual(['visible']);expect(JSON.stringify(a)).not.toContain('INTERNAL')});
 it('redacts internal financial and reason fields even when ORM objects contain extras',()=>{const i=input();Object.assign(i,{grossProfit:900,expectedBuyCost:200,actualBuyCost:300,grossMarginPct:80,costVariancePct:50});i.eta={current:'2026-09-04',previous:'2026-09-02',changedOn:i.generatedAt,reasonCode:'INTERNAL_SECRET',confidence:0.8};i.holds=[Object.assign({agencyCode:'FDA',status:'Open'},{rawNotice:'INTERNAL_SECRET'})];const a=JSON.stringify(assembleShipmentAnswers(i));expect(a).not.toMatch(/grossProfit|expectedBuyCost|actualBuyCost|grossMarginPct|costVariancePct|INTERNAL_SECRET|rawNotice/)});
 it('shows delayed ETA, active hold and nearing last free day',()=>{const i=input();i.promiseState='AT_RISK';i.eta={current:'2026-09-04',previous:'2026-09-02',changedOn:i.generatedAt,reasonCode:'PORT_CONGESTION',confidence:0.8};i.lastFreeDay='2026-09-03T12:00:00Z';i.holds=[{agencyCode:'FDA',status:'Open'}];const a=assembleShipmentAnswers(i);expect(a.eta.reason).toBe('Port congestion');expect(a.cards.filter(c=>c.status==='ATTENTION').map(c=>c.key)).toEqual(['eta','clearance','free-time'])});
});
