'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {ShipmentAnswerSet} from '@qubere/entry-proof';
const usd=(v:number|null)=>v===null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
export function AtAGlance({shipmentId}:{shipmentId:string}) {
 const [data,setData]=useState<ShipmentAnswerSet|null>(null),[error,setError]=useState('');useEffect(()=>{fetch(`/api/shipments/${shipmentId}/answers`).then(async r=>{if(!r.ok)throw new Error('Shipment answers are unavailable.');return r.json()}).then(setData).catch(e=>setError(e.message))},[shipmentId]);
 if(error)return <p role="alert" className="text-sm text-amber-800">{error}</p>;if(!data)return <p role="status" className="text-sm text-slate-500">Loading shipment answers…</p>;
 return <section className="space-y-4"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">At a glance</h2><span className="text-xs text-slate-500">{data.headline.promiseState?.replaceAll('_',' ')||data.headline.transportationStatus}</span></div><div className="grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Current arrival estimate</p><p className="text-2xl font-semibold mt-2">{data.eta.current?new Date(data.eta.current).toLocaleDateString():'Awaiting estimate'}</p>{data.eta.previous&&<p className="text-xs text-slate-500 mt-2">Previously {new Date(data.eta.previous).toLocaleDateString()}</p>}<p className="text-sm mt-2">{data.eta.reason}</p><p className="text-xs mt-3 text-slate-500">Customs: {data.headline.customsStatus}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">{data.cost.costIsPartial?'Known costs so far':'Estimated total'}</p><p className="text-2xl font-semibold mt-2">{usd(data.cost.estimatedTotalUsd)}</p><p className="text-xs text-slate-500 mt-3">Duty and fees {usd(data.cost.dutyAndFeesUsd)}</p><p className="text-xs text-slate-500 mt-1">Broker charges {usd(data.cost.brokerChargesUsd)}</p>{data.cost.costIsPartial&&<p className="text-xs text-amber-800 mt-2">Partial estimate · additional charges may apply</p>}</article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Needs from you</p><p className="text-2xl font-semibold mt-2">{data.needsFromYou.length?`${data.needsFromYou.length} open items`:'You’re up to date'}</p><ul className="space-y-2 mt-3">{data.needsFromYou.map(n=><li key={n.id} className="text-sm"><Link href={n.href} className="text-[#0071E3]">{n.label}</Link>{n.dueAt&&<span className="block text-xs text-slate-500">Due {new Date(n.dueAt).toLocaleDateString()}</span>}</li>)}</ul></article></div><div className="rounded-2xl border border-slate-200 bg-white divide-y divide-slate-100">{data.cards.map(c=><details key={c.key} className="p-4"><summary className="cursor-pointer text-sm font-medium">{c.question}{c.status==='ATTENTION'||c.status==='ACTION_REQUIRED'?<span className="ml-2 text-xs text-amber-800">Needs attention</span>:null}</summary><p className="text-sm text-slate-600 mt-3">{c.answer}</p><dl className="grid gap-2 mt-3 text-xs">{c.facts.map((f,i)=><div key={i} className="flex justify-between gap-3"><dt>{f.label}</dt><dd>{f.href?<Link href={f.href} className="text-[#0071E3]">{f.value}</Link>:f.value}</dd></div>)}</dl></details>)}</div></section>;
}
